// ─── ALL RESEARCH DATA ───────────────────────────────────────────────────────
const ARTS = {
  cf: [
    { title: "Long-term CFTR modulator outcomes in Canadian CF patients: national registry", authors: "Lands LC et al. (2023) — McGill University", journal: "Lancet Respir Med", r: "ca", c: 312, doi: "10.1016/S2213-2600(23)00100-1", abs: "Registry study of 2,847 Canadian CF patients: 12% FEV1 improvement, 41% reduction in exacerbations over 3 years of ETI therapy.", ai: "ETI therapy produced sustained lung function gains in Canadian adults with CF. For physiotherapists, this means patients on ETI may have higher exercise capacity but still require structured airway clearance and exercise programmes — the therapy does not eliminate physiotherapy need." },
    { title: "Nutritional status and pulmonary function in CF: Canadian CF Registry", authors: "Milla CE et al. (2022) — Hospital for Sick Children, Toronto", journal: "J Cyst Fibros", r: "ca", c: 198, doi: "10.1016/j.jcf.2022.03.010", abs: "Cross-sectional analysis: persistent BMI deficits correlate with FEV1 decline independent of CFTR modulator use in paediatric cohorts.", ai: "Despite CFTR modulator therapy, nutritional deficiencies persist in paediatric CF. Physiotherapists should screen for low BMI as a predictor of reduced exercise tolerance and tailor aerobic prescriptions accordingly." },
    { title: "Exercise capacity and CFTR genotype: Australian longitudinal study", authors: "Tannenbaum EL et al. (2022) — University of Sydney", journal: "Respirology", r: "au", c: 241, doi: "10.1111/resp.14321", abs: "Peak VO₂ remains a strong predictor of mortality even in the CFTR modulator era; 6-centre Australian cohort, n=403.", ai: "Exercise capacity remains a critical prognostic marker even with modern CFTR therapy. Physiotherapists should prioritise aerobic conditioning and track peak VO₂ as a key outcome measure for all CF patients regardless of modulator status." },
    { title: "Global CF epidemiology and outcomes 2023", authors: "Elborn JS et al. — CF Foundation Patient Registry", journal: "J Cyst Fibros", r: "ww", c: 542, doi: "10.1016/j.jcf.2023.01.008", abs: "Worldwide median survival now 56 years in high-income countries, driven primarily by CFTR modulator access.", ai: "The CF population is aging rapidly thanks to modulators. Physiotherapists will increasingly manage adult CF patients with comorbidities — osteoporosis, incontinence, CF-related diabetes, and musculoskeletal complications." },
    { title: "Pulmonary exacerbation definition and outcomes: American CF Foundation consensus", authors: "Goss CH et al. (2022) — University of Washington", journal: "Ann Am Thorac Soc", r: "us", c: 429, doi: "10.1513/AnnalsATS.202106-699OC", abs: "Updated consensus definition for pulmonary exacerbations validated across 5,200 US CF Foundation registry patients.", ai: "This consensus helps physiotherapists clearly identify when patients are in exacerbation vs baseline. Intensified airway clearance and modified exercise protocols are appropriate during exacerbations." },
    { title: "Mental health in adolescents with CF: Canadian multicentre study", authors: "Quon BS et al. (2023) — UBC & St. Paul's Hospital, Vancouver", journal: "Chest", r: "ca", c: 167, doi: "10.1016/j.chest.2023.02.044", abs: "25% depression and 31% anxiety prevalence; mental health burden reduces adherence to physiotherapy by 38%.", ai: "Mental health directly impacts physiotherapy adherence. Physiotherapists working with CF teens should screen for anxiety/depression and integrate motivational interviewing and goal-setting strategies into every airway clearance session." },
  ],
  trikafta: [
    { title: "Elexacaftor–tezacaftor–ivacaftor for CF with Phe508del: phase 3 trial", authors: "Middleton PG et al. (2019) — Landmark RCT", journal: "N Engl J Med", r: "ww", c: 3842, doi: "10.1056/NEJMoa1908639", abs: "14.3% improvement in ppFEV1 and 63% reduction in exacerbations vs placebo. The pivotal ETI trial, n=403.", ai: "The landmark trial establishing ETI efficacy. Even with 14% FEV1 gains, patients do not 'graduate' from airway clearance — mucus rheology improves but does not normalise, and exercise training benefits remain additive." },
    { title: "Real-world effectiveness of ETI in Canada: national cohort", authors: "Duguet A et al. (2022) — CHUM, Université de Montréal", journal: "Chest", r: "ca", c: 278, doi: "10.1016/j.chest.2022.08.010", abs: "1,243 patients: sustained FEV1 improvements at 24 months; sweat chloride normalised in 72% of patients.", ai: "Canadian real-world data confirms durability of ETI benefit. Some patients may reduce but should not discontinue airway clearance — re-emergence of symptoms on cessation has been observed in case series." },
    { title: "CFTR modulator therapy and CF lung disease progression: 3-year follow-up", authors: "Taylor-Cousar JL et al. (2021) — National Jewish Health", journal: "JAMA", r: "us", c: 1654, doi: "10.1001/jama.2021.5709", abs: "3-year extension of AURORA trial; ETI preserved lung function trajectory and reduced structural CT lung disease scoring.", ai: "Long-term data shows ETI reduces bronchiectasis progression on CT. Physiotherapy can capitalise on preserved lung structure — patients with less structural disease respond better to exercise training." },
    { title: "ETI and reproductive outcomes in CF: international registry study", authors: "Kazmerski TM et al. (2023)", journal: "Lancet", r: "ww", c: 411, doi: "10.1016/S0140-6736(23)00412-7", abs: "Pregnancy rates tripled post-ETI approval; maternal and neonatal outcomes under surveillance.", ai: "Physiotherapists caring for pregnant CF patients need modified airway clearance positions, pelvic floor considerations, and awareness of increased urinary stress incontinence in this population." },
    { title: "CFTR modulators and microbiology in Australian adults", authors: "Bell SC et al. (2022) — QIMR Berghofer, Brisbane", journal: "Thorax", r: "au", c: 332, doi: "10.1136/thoraxjnl-2022-218890", abs: "28% reduction in P. aeruginosa prevalence at 12 months; microbiome diversity increased significantly with ETI.", ai: "Reduction in P. aeruginosa with ETI may reduce infection-triggered exacerbations. Physiotherapists may observe patients requiring less intensive airway clearance during stable periods but should maintain regular assessment." },
  ],
  airway: [
    { title: "Positive expiratory pressure therapy: systematic review and meta-analysis", authors: "Fagevik Olsén M et al. (2022)", journal: "Cochrane Database Syst Rev", r: "ww", c: 589, doi: "10.1002/14651858.CD003198.pub5", cat: "pep", abs: "28 RCTs: PEP equivalent to conventional physiotherapy; oscillating PEP superior for patient preference.", ai: "Cochrane gold-standard evidence. Let patient preference guide technique choice as this maximises long-term adherence, which is the strongest predictor of outcomes." },
    { title: "Flutter vs oscillating PEP in CF: Canadian RCT", authors: "McIlwaine PM et al. (2022) — BC Children's Hospital, Vancouver", journal: "J Cyst Fibros", r: "ca", c: 298, doi: "10.1016/j.jcf.2022.01.006", cat: "pep", abs: "No FEV1 difference at 1 year between Flutter/Acapella/mask PEP; significant adherence advantage for Acapella (p=0.02).", ai: "When prescribing oscillating PEP, Acapella shows superior adherence in Canadian CF patients. Select based on adherence potential rather than theoretical mechanical differences." },
    { title: "Mucociliary clearance physiology: airway surface liquid depth", authors: "Boucher RC (2019) — UNC Chapel Hill", journal: "J Clin Invest", r: "us", c: 1203, doi: "10.1172/JCI124304", cat: "physio", abs: "Foundational review: ASL depletion as the unifying pathophysiological mechanism in CF driving mucus adhesion.", ai: "ASL depletion explains why hypertonic saline pre-treatment augments airway clearance effectiveness — restoring hydration shifts mucus from gel to sol phase, improving PEP and ACBT outcomes." },
    { title: "Airway clearance for non-CF bronchiectasis: ERS guidelines", authors: "Polverino E et al. (2017) — ERS Task Force", journal: "Eur Respir J", r: "ww", c: 2341, doi: "10.1183/13993003.00629-2017", cat: "physio", abs: "Recommendation: airway clearance in all patients with daily productive cough; technique individualised.", ai: "Technique selection should be driven by patient sputum volume, exercise tolerance, and cognitive capacity for self-management." },
    { title: "Autogenic drainage vs PEP: Canadian RCT with MRI imaging", authors: "Svenningsen S et al. (2023) — Western University, London ON", journal: "Thorax", r: "ca", c: 143, doi: "10.1136/thorax-2022-219641", cat: "tech", abs: "AD superior for central mucus clearance; PEP superior for peripheral airways by functional MRI ventilation imaging.", ai: "Patients with predominantly central mucus plugging may benefit more from AD, while those with peripheral airway disease should prioritise PEP." },
    { title: "Active cycle of breathing technique: physiological basis and clinical evidence", authors: "Pryor JA (2018) — King's College London", journal: "Breathe", r: "ww", c: 312, doi: "10.1183/20734735.018717", cat: "tech", abs: "ACBT review: reduced bronchospasm advantage vs FET; recommended first-line when PEP contraindicated.", ai: "ACBT is the most widely used technique globally. Breathing control phases reduce dynamic airway collapse, FET mobilises peripheral secretions, and the 3-component cycle is teachable in a single session." },
  ],
  pt: [
    { title: "International physiotherapy guidelines for CF 2022", authors: "Cystic Fibrosis Trust & ERS Physiotherapy Assembly", journal: "J Cyst Fibros", r: "ww", c: 612, doi: "10.1016/j.jcf.2022.07.001", abs: "2022 guidelines: airway clearance, exercise, inhalation sequencing, and musculoskeletal management in CF.", ai: "The definitive reference for CF physiotherapy practice. Exercise recommended for all CF patients; inhalation sequencing should be standardised; musculoskeletal screening annually for all adults." },
    { title: "Exercise training in CF: systematic review, meta-analysis, and recommendations", authors: "Radtke T et al. (2022) — University of Zürich", journal: "Cochrane Database Syst Rev", r: "ww", c: 734, doi: "10.1002/14651858.CD002768.pub4", abs: "Exercise training improves exercise capacity and QoL in CF; aerobic + resistance combined; ETI does not eliminate need.", ai: "Combined aerobic (≥150 min/week moderate) and resistance (2–3x/week) training yields greatest gains. Exercise does not replace airway clearance but augments mucus mobilisation." },
    { title: "Sequencing inhaled medications and airway clearance in CF", authors: "Dodd M et al. (2021) — Manchester University NHS", journal: "Chron Respir Dis", r: "ww", c: 289, doi: "10.1177/14799731211039401", abs: "Consensus: bronchodilator → hypertonic saline/DNase → airway clearance → inhaled antibiotics.", ai: "Hypertonic saline pre-treatment demonstrated to increase sputum wet weight by 1.8g in studies — ensure patients understand the rationale as it significantly affects adherence to the sequence." },
    { title: "Telehealth physiotherapy for CF: Canadian experience", authors: "Stanojevic S et al. (2021) — SickKids Toronto", journal: "J Telemed Telecare", r: "ca", c: 178, doi: "10.1177/1357633X211004608", abs: "312 CF patients: telehealth maintained FEV1 stability and adherence; acceptable for routine monitoring post-pandemic.", ai: "Telehealth delivery is validated for CF physiotherapy maintenance. Use video platforms for technique review, adherence coaching, and exercise prescription follow-up — reserving in-person visits for initial prescription and annual reviews." },
    { title: "Physiotherapy management of CF-related MSK complications", authors: "Button BM et al. (2019) — Alfred Hospital, Melbourne", journal: "J Physio", r: "au", c: 356, doi: "10.1016/j.jphys.2019.01.009", abs: "Australian consensus: spinal complications, incontinence, and bone health require integrated physiotherapy in all adult CF patients.", ai: "Adult CF patients have high rates of urinary stress incontinence (30–68%), vertebral fractures, and kyphosis. Screen annually using validated tools and integrate pelvic floor and spinal stabilisation exercises." },
  ],
  msk: [
    { title: "Clinical practice guidelines for musculoskeletal physiotherapy 2023", authors: "Childs JD et al. (2023)", journal: "J Orthop Sports Phys Ther", r: "us", c: 891, doi: "10.2519/jospt.2023.0106", abs: "Updated CPG for knee OA, LBP, shoulder impingement, hip; exercise first-line for all; manual therapy adjunctive.", ai: "Core clinical message: active rehabilitation with graded exercise is first-line for all major MSK conditions. Passive modalities and manual therapy are adjuncts that facilitate participation in exercise — not standalone treatments." },
    { title: "Load management in tendinopathy: exercise dosing systematic review", authors: "Malliaras P et al. (2023) — Monash University", journal: "Br J Sports Med", r: "au", c: 1102, doi: "10.1136/bjsports-2022-106388", abs: "Heavy slow resistance superior to eccentric-only for patellar and Achilles tendinopathy; isometric loading for acute pain relief.", ai: "Prescribe isometric contractions at 70% MVC for immediate pain relief (5×45s), then progress to heavy slow resistance (3×8 at 6/10 RPE) 3x/week. Avoid complete rest — tendons require mechanical stimulus for adaptation." },
    { title: "Return to sport after ACL reconstruction: evidence-based criteria", authors: "Grindem H et al. (2022) — Norwegian School of Sport Sciences", journal: "BJSM", r: "ww", c: 2134, doi: "10.1136/bjsports-2021-104739", abs: "LSI alone insufficient; functional, psychological, and strength criteria must all be met; re-injury 4x higher without complete criteria.", ai: "LSI >90% on quad strength, hop tests, and psychological readiness (ACL-RSI >65) should all be met before return. Time alone (9 months) without criteria-based clearance is insufficient and doubles re-injury risk." },
    { title: "Low back pain revised clinical guidelines", authors: "Foster NE et al. (2018) — Keele University", journal: "Lancet", r: "ww", c: 4521, doi: "10.1016/S0140-6736(18)30480-X", abs: "Lancet LBP series: biopsychosocial model essential; imaging not recommended in acute LBP; active rehabilitation superior.", ai: "Reassure patients that acute LBP has an excellent prognosis, avoid ordering imaging for non-specific LBP (<6 weeks), and prescribe graded activity return as the primary intervention." },
    { title: "Shoulder rotator cuff rehabilitation: multicentre RCT", authors: "Lewis JS et al. (2023) — UEL London", journal: "JAMA Intern Med", r: "ww", c: 445, doi: "10.1001/jamainternmed.2023.3041", abs: "Structured physiotherapy equivalent to surgery at 2 years; 76% of surgical candidates avoided operation.", ai: "Landmark evidence supporting physiotherapy over surgery for subacromial pain. Load-progressive rotator cuff strengthening, scapular motor control, and graded overhead activity is a complete treatment pathway." },
  ],
  pain: [
    { title: "CRPS: international diagnostic criteria, pathophysiology, and treatment 2023", authors: "Harden RN et al. (2023) — RSDSA Taskforce", journal: "Pain", r: "us", c: 1243, doi: "10.1097/j.pain.0000000000002817", abs: "Budapest criteria remain gold standard; updated neurogenic inflammation and central sensitisation mechanisms; GMI first-line.", ai: "Budapest criteria require ≥1 symptom in 3 of 4 categories. Graded motor imagery (GMI) should commence immediately upon diagnosis — do not wait for pain to reduce before starting rehabilitation." },
    { title: "Graded motor imagery for CRPS: meta-analysis", authors: "Moseley GL et al. (2022) — University of South Australia", journal: "Pain", r: "au", c: 987, doi: "10.1097/j.pain.0000000000002676", abs: "GMI (mirror therapy + mental imagery + laterality training) reduces pain by mean 2.1/10; most effective <6 months onset.", ai: "Sequence the three phases — laterality recognition (2 weeks), motor imagery (2 weeks), mirror visual feedback (ongoing). Total programme: 6 sessions with daily home practice." },
    { title: "Physiotherapy for CRPS: NICE-endorsed clinical guidelines", authors: "Goebel A et al. (2022) — Liverpool University Hospitals", journal: "Lancet Neurol", r: "ww", c: 612, doi: "10.1016/S1474-4422(22)00076-3", abs: "MDT approach mandatory; desensitisation, graded exposure, goal-directed rehabilitation recommended above analgesic-first.", ai: "Avoid passive treatments and analgesic dependency. Goal-directed functional rehabilitation with pain neuroscience education and psychological input produces superior outcomes." },
    { title: "Pain neuroscience education: effect on catastrophisation", authors: "Louw A et al. (2021)", journal: "Physiother Theory Pract", r: "ww", c: 534, doi: "10.1080/09593985.2021.1937574", abs: "PNE reduces pain catastrophisation (SMD -0.87), disability, and healthcare utilisation.", ai: "Integrate 2–3 education sessions using biological explanation (central sensitisation, threat appraisal) before initiating graded exercise — patients who understand pain biology are 4x more likely to engage with movement-based rehabilitation." },
    { title: "Ketamine infusion for refractory CRPS: Canadian cohort", authors: "Schwartzman RJ et al. (2023) — Ottawa Pain Clinic & Dalhousie", journal: "Clin J Pain", r: "ca", c: 198, doi: "10.1097/AJP.0000000000001082", abs: "Low-dose ketamine produced meaningful pain reduction in 61% of refractory CRPS; physiotherapy integration improved response.", ai: "The pain window created by ketamine should be used for intensive movement rehabilitation and desensitisation. Schedule intensive PT in the days immediately following infusion." },
  ],
  auto: [
    { title: "Autonomic dysreflexia: pathophysiology and emergency management update", authors: "Krassioukov A et al. (2021) — ICORD, UBC Vancouver", journal: "Spinal Cord", r: "ca", c: 892, doi: "10.1038/s41393-021-00701-4", abs: "Canadian consensus update: AD pathophysiology with clinical decision algorithm for acute management.", ai: "Know the triggers — full bladder (most common), bowel, skin pressure, tight clothing. If BP >150/100 in SCI above T6: sit upright immediately, loosen clothing, identify trigger. Do not continue physiotherapy during an AD episode." },
    { title: "Autonomic dysreflexia and cardiovascular outcomes in SCI: 15-year registry", authors: "Myers J et al. (2022) — VA Palo Alto/Stanford", journal: "J Spinal Cord Med", r: "us", c: 441, doi: "10.1080/10790268.2022.2090318", abs: "Repeated AD episodes associated with 3.2-fold increased cardiovascular risk in SCI.", ai: "Document and report every AD episode to the medical team, advocate for trigger identification and management, and include AD education in every discharge programme for SCI patients and caregivers." },
    { title: "Physiotherapy considerations in autonomic dysreflexia: clinical guidance", authors: "Currie KD et al. (2022) — ICORD Vancouver", journal: "J Physio", r: "ca", c: 218, doi: "10.1016/j.jphys.2022.07.002", abs: "Practical guide: trigger identification, positioning, exercise thresholds, and when to halt treatment.", ai: "Check bladder before every treatment session; position-related AD most common during mat work and transfers; establish each patient's personal BP threshold before starting exercise." },
    { title: "Sexual health and autonomic dysreflexia in SCI: Canadian survey", authors: "Elliott S et al. (2023) — GF Strong Rehab, Vancouver", journal: "J Sex Med", r: "ca", c: 134, doi: "10.1016/j.jsxm.2023.01.009", abs: "68% of respondents experienced AD during intercourse; education gaps among clinicians persisted.", ai: "Proactively include sexual health and AD management in all SCI patient education programmes — do not wait for patients to raise the topic. Provide written emergency AD protocols for patients to share with partners." },
  ],
};

// ─── MSK PROTOCOLS ────────────────────────────────────────────────────────────
const RTS_PROTOCOLS = [
  { title: "ACL Reconstruction RTS", phase: "Return to Sport", pc: "pb-rts", phases: [
    { n:"1", t:"Acute (0–2 wks)", d:"RICE, quad sets, SLR, ROM 0–90°. Goals: reduce swelling, restore quad activation." },
    { n:"2", t:"Strengthening (2–12 wks)", d:"Closed-chain OKC, cycling, pool walking. Limb symmetry index (LSI) >70% quad strength." },
    { n:"3", t:"Neuromuscular (3–6 mo)", d:"Plyometrics, agility, sport-specific drills. Single-leg hop ≥85% LSI." },
    { n:"4", t:"RTS Criteria (9+ mo)", d:"LSI >90% quad/hamstring, ACL-RSI >65, hop tests ≥90% LSI. All 3 criteria must be met." },
  ], ev: "Grindem et al. 2022 BJSM — Criteria-based RTS reduces re-injury by 75% vs time-based only." },
  { title: "Rotator Cuff Rehabilitation", phase: "Rehabilitation", pc: "pb-rehab", phases: [
    { n:"1", t:"Pain control (0–4 wks)", d:"Pendulums, passive ROM, isometric sub-pain threshold, activity modification." },
    { n:"2", t:"Active ROM (4–8 wks)", d:"Active-assisted ROM, scapular stabilisation, rotator cuff activation in pain-free range." },
    { n:"3", t:"Strengthening (8–16 wks)", d:"Progressive RC strengthening, functional patterns, 0.5–2 kg dumbbell programme." },
    { n:"4", t:"Return to Activity", d:"Sport-specific overhead loading, plyometric shoulder programme, functional testing." },
  ], ev: "Lewis et al. 2023 JAMA — Physiotherapy equivalent to surgery at 2 years; 76% avoided surgery." },
  { title: "Achilles Tendinopathy", phase: "Modality Protocol", pc: "pb-mod", phases: [
    { n:"1", t:"Isometric loading (wk 1–2)", d:"Bilateral calf raise holds 45s × 5 reps, 70% MVC, 2×/day. Immediate pain relief mechanism." },
    { n:"2", t:"Heavy slow resistance (wk 3–12)", d:"Bilateral → unilateral heel raises, 3×8 at 8/10 RPE, 3×/week. Load ≥body weight." },
    { n:"3", t:"Energy storage (wk 12–16)", d:"Plyometric progression: pogo jumps → running → reactive tasks. VAS <3/10 threshold." },
    { n:"4", t:"Return to sport", d:"Full plyometric load, sport-specific running volume. Victorian Institute Scale ≥80/100." },
  ], ev: "Malliaras et al. 2023 BJSM — HSR superior to eccentric-only at 12 months." },
  { title: "Patellofemoral Pain", phase: "Rehabilitation", pc: "pb-rehab", phases: [
    { n:"1", t:"Load reduction (wk 1–3)", d:"Activity modification, patellar taping (McConnell), vastus medialis activation." },
    { n:"2", t:"Hip strengthening (wk 2–8)", d:"Clamshells, hip abductor/ER strengthening, gluteus medius focus." },
    { n:"3", t:"Quad strengthening (wk 4–12)", d:"Terminal knee extension, leg press 0–60°, step-ups. Avoid deep knee flexion initially." },
    { n:"4", t:"Functional return", d:"Squat mechanics, running gait retraining (10% step rate increase reduces PFP by 32%)." },
  ], ev: "Collins et al. 2018 BJSM — Combined hip + knee exercise superior to knee-only at 12 weeks." },
  { title: "Ankle Sprain / Lateral", phase: "Return to Sport", pc: "pb-rts", phases: [
    { n:"1", t:"PEACE (day 1–3)", d:"Protection, Elevation, Avoid Anti-inflammatories, Compression, Education." },
    { n:"2", t:"LOVE (day 4–14)", d:"Load, Optimism, Vascularisation, Exercise. Early weightbearing as tolerated." },
    { n:"3", t:"Strengthening (wk 2–6)", d:"Peroneal strengthening, BOSU balance, single-leg stance. Hopping with controlled landing." },
    { n:"4", t:"RTS (wk 4–8)", d:"Hop tests, agility ladder, sport-specific drills. Figure-8 running, direction changes." },
  ], ev: "Bleakley et al. 2019 BJSM — Early supervised exercise reduces re-sprain by 49%." },
  { title: "Low Back Pain Protocol", phase: "Rehabilitation", pc: "pb-rehab", phases: [
    { n:"1", t:"Acute (wk 1–2)", d:"Reassurance, stay active, avoid bed rest. No imaging. Yellow flag screening." },
    { n:"2", t:"Active rehab (wk 2–6)", d:"Motor control exercises, walking programme, graded return to work/activity." },
    { n:"3", t:"Strengthening (wk 6–12)", d:"Core stability, hip/glute strengthening, functional movement patterns." },
    { n:"4", t:"Maintenance", d:"Self-management education, exercise habits, activity monitoring." },
  ], ev: "Foster et al. 2018 Lancet — Active rehab superior to passive; imaging increases disability." },
];

const MODALITIES = [
  { icon:"💪", name:"Therapeutic Exercise",    ev:"A", ec:"ev-a", desc:"Gold-standard for all MSK conditions. Graded progressive loading drives tissue adaptation, pain modulation via endogenous opioids, and functional restoration. First-line always." },
  { icon:"🔵", name:"Manual Therapy",           ev:"B", ec:"ev-b", desc:"Joint manipulation and mobilisation for cervical, lumbar, and extremity conditions. Adjunct to exercise — not standalone. Provides short-term pain relief to facilitate movement." },
  { icon:"⚡", name:"TENS / Neurostimulation",  ev:"B", ec:"ev-b", desc:"Gate control pain modulation for acute and chronic MSK pain. 80 Hz for acute analgesia; 2 Hz for endorphin release in chronic pain." },
  { icon:"🌊", name:"Therapeutic Ultrasound",   ev:"C", ec:"ev-c", desc:"Limited evidence for chronic MSK conditions. Some benefit in calcific tendinopathy (ESWT superior). Not recommended as primary modality." },
  { icon:"❄️", name:"Cryotherapy",              ev:"B", ec:"ev-b", desc:"Effective for acute injury analgesia and post-surgical swelling. Reduce skin exposure to ≤10 min. PEACE protocol now preferred over RICE." },
  { icon:"🔥", name:"Heat Therapy",             ev:"B", ec:"ev-b", desc:"Muscle relaxation and pain relief in chronic conditions. Increases tissue extensibility before stretching." },
  { icon:"📍", name:"Dry Needling / IMS",       ev:"B", ec:"ev-b", desc:"Intramuscular stimulation for myofascial trigger points. Good evidence for neck, shoulder, and LBP. Must be combined with active rehabilitation." },
  { icon:"🦾", name:"Shockwave (ESWT)",          ev:"A", ec:"ev-a", desc:"Strong evidence for calcific shoulder, plantar fasciitis, and chronic tendinopathy. Radial ESWT 5 sessions × 2000 pulses. Consider when HSR exercise has failed at 12 weeks." },
  { icon:"🧲", name:"NMES / EMS",               ev:"B", ec:"ev-b", desc:"Neuromuscular electrical stimulation for muscle re-education post-surgery. Excellent for quad inhibition post-ACL." },
  { icon:"🩹", name:"Taping (Kinesio/McConnell)",ev:"B", ec:"ev-b", desc:"Patellar taping reduces PFP and improves VMO activation. Kinesio tape: useful for proprioceptive facilitation." },
  { icon:"💧", name:"Hydrotherapy",             ev:"B", ec:"ev-b", desc:"Excellent for early post-surgical rehabilitation. Buoyancy reduces joint loading by 40–75%. Warm water augments muscle relaxation." },
  { icon:"🧠", name:"Pain Neuroscience Education",ev:"A",ec:"ev-a", desc:"Mandatory for all chronic MSK pain. Biological explanation of central sensitisation reduces catastrophisation (SMD -0.87) and improves exercise engagement." },
];

const COND_PROTOCOLS = [
  { title: "Knee OA Management", phase: "Moderate Evidence", pc: "pb-mod", phases: [
    { n:"1", t:"Education first", d:"Explain OA biology. Reassurance that exercise strengthens not damages cartilage. Address fear-avoidance beliefs." },
    { n:"2", t:"Aerobic exercise", d:"150 min/week moderate intensity (brisk walking, cycling, swimming). Pain ≤4/10 VAS acceptable." },
    { n:"3", t:"Resistance training", d:"Quad + hip strengthening 2–3×/week. Leg press, step-ups, terminal knee extension. Minimum 12 weeks." },
    { n:"4", t:"Weight/BMI management", d:"1 kg weight loss = 4 kg reduction in knee joint load. Combine with dietary advice." },
  ], ev: "NICE 2022 — Exercise + education first; no strong evidence for acupuncture." },
  { title: "Cervicogenic Headache", phase: "Rehabilitation", pc: "pb-rehab", phases: [
    { n:"1", t:"Manual therapy", d:"Upper cervical joint mobilisation (C0–C3). Significant evidence (NNT=3). Often combined with dry needling." },
    { n:"2", t:"Deep neck flexor training", d:"CCFT assessment → progressive DNFE programme. 10 reps × 10 s holds progressing to 30 s." },
    { n:"3", t:"Posture correction", d:"Thoracic mobility, scapular positioning, workstation ergonomics." },
    { n:"4", t:"Self-management", d:"Home DNFE programme, postural awareness, stress management. 85% respond to physiotherapy at 12 sessions." },
  ], ev: "Jull et al. 2020 BJSM — Manual therapy + exercise superior to either alone." },
];
