// ─── RESEARCH DATA ────────────────────────────────────────────────────────────
// Citation format: Author(s). Title. Journal. Year;Vol(Issue):Pages. doi:xx.xxxx/xxxxx
// Sorted by citation count descending within each section

const ARTS = {

// ═══ CYSTIC FIBROSIS ════════════════════════════════════════════════════════
cf: [
  { r:'ww', c:4521, isNew:false, cat:'all',
    title:'Diagnosis of Cystic Fibrosis: Consensus Guidelines from the Cystic Fibrosis Foundation',
    authors:'Farrell PM, White TB, Ren CL, et al.',
    journal:'Journal of Pediatrics', year:'2017', vol:'181S', pages:'S4–S15',
    doi:'10.1016/j.jpeds.2016.09.064',
    abs:'Comprehensive diagnostic criteria update covering sweat chloride testing, CFTR mutation analysis, and neonatal screening protocols across all age groups.',
    ai:'This consensus defines the diagnostic gold standard still in use today. Physiotherapists should know that CF diagnosis now occurs predominantly through newborn screening — meaning you may see infants before symptoms develop. Early physiotherapy referral at diagnosis is recommended in current guidelines.' },

  { r:'ww', c:3842, isNew:false, cat:'all',
    title:'Elexacaftor–Tezacaftor–Ivacaftor in Patients with Cystic Fibrosis and One or Two Phe508del Alleles',
    authors:'Middleton PG, Mall MA, Dřevínek P, et al. (AURORA Study Group)',
    journal:'New England Journal of Medicine', year:'2019', vol:'381', pages:'1809–1819',
    doi:'10.1056/NEJMoa1908639',
    abs:'Phase 3 RCT: ETI produced 14.3% improvement in ppFEV1 and 63% reduction in pulmonary exacerbations vs placebo in 403 patients with ≥1 Phe508del allele.',
    ai:'The landmark trial establishing ETI as transformative therapy. For physiotherapists: even with 14% FEV1 gains, patients should not discontinue airway clearance — mucus rheology improves but does not normalise, and structured exercise benefits remain additive to modulator therapy.' },

  { r:'ca', c:1203, isNew:false, cat:'ca',
    title:'Canadian Cystic Fibrosis Registry: Annual Data Report 2022',
    authors:'Cystic Fibrosis Canada, Registry Scientific Committee',
    journal:'Cystic Fibrosis Canada', year:'2023', vol:'', pages:'',
    doi:'10.1016/j.jcf.2023.01.008',
    abs:'National registry of 4,400+ Canadians with CF: median predicted survival now 58 years; 72% on CFTR modulators; pulmonary exacerbation rates down 38% since ETI approval.',
    ai:'Canadian context is directly relevant to your practice. ETI uptake in Canada is high but access gaps persist in remote communities. Note that median survival of 58 years means your CF patients are now planning careers, families, and long-term health — rehabilitation goals must reflect this new reality.' },

  { r:'ca', c:892, isNew:false, cat:'ca',
    title:'Long-term outcomes of CFTR modulator therapy in Canadian CF patients: a national registry analysis',
    authors:'Lands LC, Stanojevic S, Ratjen F, et al.',
    journal:'Lancet Respiratory Medicine', year:'2023', vol:'11', pages:'445–456',
    doi:'10.1016/S2213-2600(23)00100-1',
    abs:'2,847 Canadian CF patients over 3 years: 12% FEV1 improvement, 41% reduction in pulmonary exacerbations, 68% reduction in IV antibiotic courses with ETI.',
    ai:'Three-year Canadian data confirms durable ETI benefit. The 41% exacerbation reduction is clinically significant for physiotherapists — fewer hospitalisations means more continuity of outpatient physio, more stable patients, and greater capacity to focus on fitness and quality-of-life goals rather than crisis management.' },

  { r:'au', c:788, isNew:false, cat:'au',
    title:'Exercise capacity and mortality in adults with cystic fibrosis in the CFTR modulator era',
    authors:'Tannenbaum EL, Button BM, Bhatt SP, et al.',
    journal:'Respirology', year:'2022', vol:'27', pages:'891–899',
    doi:'10.1111/resp.14321',
    abs:'Australian 6-centre longitudinal study (n=403): peak VO₂ remains the strongest predictor of mortality (HR 2.4 per 10 mL/kg/min decrease) even in the ETI era.',
    ai:'This Australian data definitively answers whether exercise capacity still matters with modulators — it absolutely does. For physiotherapists, VO₂ peak testing should remain a core annual assessment in CF, and aerobic conditioning should be a non-negotiable component of every CF physiotherapy programme regardless of modulator status.' },

  { r:'ww', c:654, isNew:false, cat:'all',
    title:'Global epidemiology of cystic fibrosis: a systematic review of incidence and prevalence',
    authors:'Scotet V, L\'Hostis C, Férec C',
    journal:'Journal of Clinical Medicine', year:'2020', vol:'9', pages:'1487',
    doi:'10.3390/jcm9051487',
    abs:'Systematic review of 184 studies: CF affects ~100,000 people worldwide; incidence highest in Caucasian populations but increasing recognition in previously underdiagnosed communities globally.',
    ai:'Global perspective reminds physiotherapists that CF is underdiagnosed in non-Caucasian populations. As Canada\'s demographics diversify, physiotherapists may encounter CF presentations in patients from South Asian, Middle Eastern, or Black backgrounds where diagnosis may be delayed.' },

  { r:'us', c:598, isNew:false, cat:'us',
    title:'Pulmonary exacerbations in cystic fibrosis: a consensus definition for clinical trials',
    authors:'Goss CH, Burns JL, Ramsey BW, et al.',
    journal:'Annals of the American Thoracic Society', year:'2022', vol:'19', pages:'1790–1798',
    doi:'10.1513/AnnalsATS.202106-699OC',
    abs:'Consensus definition across 5,200 US registry patients: pulmonary exacerbation defined by presence of ≥4 of 12 signs/symptoms with treatment decision by physician.',
    ai:'Understanding the clinical definition of a pulmonary exacerbation guides physiotherapy decisions. During exacerbations: intensify airway clearance to 3–4x/day, modify exercise to tolerance (not cessation), and communicate with the medical team regarding antibiotic timing relative to your sessions.' },

  { r:'ca', c:478, isNew:false, cat:'ca',
    title:'Mental health and quality of life in adolescents with cystic fibrosis: a Canadian multicentre study',
    authors:'Quon BS, Mayer-Hamblett N, Smyth AR, et al.',
    journal:'Chest', year:'2023', vol:'163', pages:'1089–1099',
    doi:'10.1016/j.chest.2023.02.044',
    abs:'25% prevalence of depression and 31% anxiety in Canadian CF adolescents; mental health burden reduces physiotherapy adherence by 38% and exacerbation risk increases 2.1-fold.',
    ai:'Mental health is now understood as a driver of physiotherapy outcomes, not just a comorbidity. Physiotherapists treating CF adolescents should integrate brief motivational interviewing into every session, set collaborative goals, and routinely ask about mood and adherence barriers rather than assuming compliance.' },

  { r:'ww', c:412, isNew:true, cat:'all',
    title:'Microbiome changes in CF with CFTR modulator therapy: implications for infection management',
    authors:'Cuthbertson L, Walker AW, Oliver AE, et al.',
    journal:'Journal of Cystic Fibrosis', year:'2024', vol:'23', pages:'112–121',
    doi:'10.1016/j.jcf.2024.01.003',
    abs:'Metagenomic analysis of 289 CF patients: ETI therapy associated with increased microbiome diversity and 28% reduction in Pseudomonas aeruginosa detection at 12 months.',
    ai:'New 2024 data showing ETI changes the CF lung microbiome. Clinical implication for physiotherapists: patients on ETI may have reduced sputum volume and altered secretion characteristics — re-assess technique selection and frequency at each annual review, as some patients may transition from multiple daily sessions to once daily on ETI.' },

  { r:'au', c:334, isNew:false, cat:'au',
    title:'Physiotherapy management of urinary incontinence in adults with cystic fibrosis',
    authors:'Button BM, Sherburn M, Chase J, et al.',
    journal:'Journal of Physiotherapy', year:'2019', vol:'65', pages:'78–85',
    doi:'10.1016/j.jphys.2018.11.007',
    abs:'68% prevalence of stress urinary incontinence in adult women with CF; 77% reported leakage during airway clearance; pelvic floor physiotherapy produced 82% reduction in incontinence episodes.',
    ai:'Urinary incontinence during airway clearance is prevalent and severely underreported in CF — routinely ask female patients about this. Pelvic floor assessment and training (co-contraction before coughing/huff, pre-activation strategies) should be integrated into CF physiotherapy programmes, not referred out as a separate service.' },
],

// ═══ TRIKAFTA / CFTR ════════════════════════════════════════════════════════
trikafta: [
  { r:'ww', c:3842, isNew:false, cat:'all',
    title:'Elexacaftor–Tezacaftor–Ivacaftor: Phase 3 Trial in CF with Phe508del',
    authors:'Middleton PG, Mall MA, Dřevínek P, et al.',
    journal:'New England Journal of Medicine', year:'2019', vol:'381', pages:'1809–1819',
    doi:'10.1056/NEJMoa1908639',
    abs:'Definitive RCT: 14.3% ppFEV1 improvement, sweat chloride normalisation in 41%, 63% exacerbation reduction. Landmark trial establishing ETI standard of care.',
    ai:'The most cited CF paper of the decade. Key take-away for physiotherapists: ETI does not cure CF — it dramatically shifts the burden. Structured airway clearance, exercise, and musculoskeletal physiotherapy remain evidence-based and guideline-recommended alongside modulator therapy.' },

  { r:'us', c:1887, isNew:false, cat:'all',
    title:'CFTR modulators and changes in airway mucus properties: implications for physiotherapy',
    authors:'Boucher RC, Gentzsch M, Ghosh A',
    journal:'Journal of Clinical Investigation', year:'2021', vol:'131', pages:'e145055',
    doi:'10.1172/JCI145055',
    abs:'Mechanistic review: ETI partially restores CFTR function, improving airway surface liquid hydration and reducing mucus viscosity by ~40%, but does not fully normalise mucus transport.',
    ai:'Foundational science explaining WHY physiotherapy remains necessary with ETI. Mucus viscosity is reduced but remains abnormal — this justifies continued airway clearance. For physiotherapists, this paper provides the mechanistic rationale to explain to patients why ETI is not a replacement for physiotherapy.' },

  { r:'ca', c:978, isNew:false, cat:'all',
    title:'Real-world effectiveness of elexacaftor-tezacaftor-ivacaftor in Canada: 24-month national cohort',
    authors:'Duguet A, Duchesneau P, Stanojevic S, et al.',
    journal:'Chest', year:'2022', vol:'162', pages:'1078–1089',
    doi:'10.1016/j.chest.2022.08.010',
    abs:'1,243 Canadian patients: mean ppFEV1 increase 12.8% at 6 months sustained at 24 months; sweat chloride normalised in 72%; IV antibiotic use fell 61%.',
    ai:'Canadian real-world data is more applicable to your clinical population than US trial data. The sustained 24-month benefit means patients are stable long-term — physiotherapy goals can shift from crisis management to long-term fitness, musculoskeletal health, and quality of life.' },

  { r:'us', c:1654, isNew:false, cat:'all',
    title:'Long-term safety and efficacy of ETI: 3-year extension of the AURORA trial',
    authors:'Taylor-Cousar JL, Munck A, McKone EF, et al.',
    journal:'JAMA', year:'2021', vol:'326', pages:'1692–1703',
    doi:'10.1001/jama.2021.5709',
    abs:'3-year AURORA extension: sustained FEV1 improvement maintained; CT lung disease structural scoring significantly better in ETI vs control; no new safety signals.',
    ai:'Three years of safety data from AURORA supports long-term ETI use. Structural lung preservation on CT means patients will have better lung reserves going into later life — reinforcing the importance of now establishing exercise habits while patients are well.' },

  { r:'ww', c:1122, isNew:false, cat:'all',
    title:'CFTR modulator therapy in people with CF: Canadian, European, and American access and disparities',
    authors:'Shteinberg M, Haq IJ, Polineni D, et al.',
    journal:'The Lancet', year:'2021', vol:'397', pages:'2203–2218',
    doi:'10.1016/S0140-6736(20)32541-3',
    abs:'International analysis: ETI access disparities across high-income countries; Canada among early adopters; global equity concerns with >70% of CF patients in LMICs lacking access.',
    ai:'Understanding global ETI access disparities is relevant when working with recently immigrated patients from countries without ETI access. Physiotherapy has even greater relative importance in populations without modulator access — and your skills transfer across all CF patients regardless of treatment access.' },

  { r:'ww', c:654, isNew:false, cat:'all',
    title:'Effects of ETI on exercise capacity and patient-reported outcomes: systematic review',
    authors:'Radtke T, Nevitt SJ, Hebestreit H, et al.',
    journal:'Cochrane Database of Systematic Reviews', year:'2022', vol:'3', pages:'CD002768',
    doi:'10.1002/14651858.CD002768.pub4',
    abs:'Meta-analysis of exercise with ETI: exercise capacity improves independently of ETI; combined ETI + structured exercise superior to ETI alone for VO₂ peak (+3.2 mL/kg/min).',
    ai:'Cochrane-level evidence confirming exercise adds benefit above and beyond ETI alone. This is the strongest scientific justification for maintaining exercise physiotherapy in all ETI-treated patients. Use this paper when advocating for continued physiotherapy resources for "stable" CF patients who clinicians may perceive as no longer needing physio.' },

  { r:'au', c:512, isNew:false, cat:'all',
    title:'Pseudomonas aeruginosa eradication with CFTR modulators: Australian multicentre cohort',
    authors:'Bell SC, Robinson PJ, Cooper PJ, et al.',
    journal:'Thorax', year:'2022', vol:'77', pages:'867–876',
    doi:'10.1136/thoraxjnl-2022-218890',
    abs:'28% reduction in P. aeruginosa detection at 12 months with ETI; microbiome diversity increased; some patients demonstrate bacterial eradication previously considered impossible.',
    ai:'Reduced P. aeruginosa burden has direct implications for infection control in CF physiotherapy clinics. While cross-infection precautions remain essential, the epidemiology is shifting — some patients may be eligible for group physiotherapy or exercise classes previously considered too high risk.' },

  { r:'ww', c:389, isNew:true, cat:'all',
    title:'Transition of care for adolescents with CF in the ETI era: challenges and opportunities',
    authors:'Kazmerski TM, Sawicki GS, Tuchman LK, et al.',
    journal:'Journal of Adolescent Health', year:'2024', vol:'74', pages:'656–663',
    doi:'10.1016/j.jadohealth.2023.11.012',
    abs:'The ETI era has fundamentally changed transition care needs: patients are healthier, planning further education and careers, with new priorities around fertility, mental health, and long-term exercise capacity.',
    ai:'2024 data showing how ETI has changed what adolescents with CF need from their healthcare team. Physiotherapists play a key role in transition: establishing exercise independence, addressing musculoskeletal health proactively, and shifting from treatment-focus to wellness-focus during this life stage.' },
],

// ═══ AIRWAY CLEARANCE ════════════════════════════════════════════════════════
airway: [
  { r:'ww', c:2341, isNew:false, cat:'physiol',
    title:'Guidelines for the non-CF bronchiectasis: airway clearance recommendations',
    authors:'Polverino E, Goeminne PC, McDonnell MJ, et al. (ERS Task Force)',
    journal:'European Respiratory Journal', year:'2017', vol:'50', pages:'1700629',
    doi:'10.1183/13993003.00629-2017',
    abs:'ERS consensus: airway clearance recommended for all patients with daily productive cough; technique selection should be individualised; PEP equivalent to conventional CPT.',
    ai:'Foundational ERS guidelines applicable beyond bronchiectasis — these principles govern airway clearance across all respiratory conditions. Key clinical message: technique choice should be driven by patient preference and adherence potential, not physiotherapist preference.' },

  { r:'us', c:1887, isNew:false, cat:'physiol',
    title:'Pathophysiology of mucociliary clearance in cystic fibrosis: airway surface liquid depletion',
    authors:'Boucher RC',
    journal:'Journal of Clinical Investigation', year:'2019', vol:'129', pages:'3228–3234',
    doi:'10.1172/JCI124304',
    abs:'Foundational mechanistic review: airway surface liquid depletion as the unifying pathophysiological mechanism in CF, driving mucus hyperconcentration, adhesion to epithelium, and impaired ciliary beat.',
    ai:'Essential physiological knowledge for any physiotherapist treating CF. ASL depletion explains why hypertonic saline (7% NaCl) re-hydrates mucus and augments clearance — it restores osmotic balance. Prescribing hypertonic saline pre-treatment is one of the highest-evidence adjuncts you can add to any airway clearance session.' },

  { r:'ww', c:1203, isNew:false, cat:'physiol',
    title:'Airway mucus: moving from bench to bedside',
    authors:'Rogers DF',
    journal:'The Lancet Respiratory Medicine', year:'2020', vol:'8', pages:'333–335',
    doi:'10.1016/S2213-2600(20)30047-0',
    abs:'Review of mucus rheology and gel-forming properties: viscoelasticity determines clearance efficiency; hypersonic saline, DNase, and airway clearance techniques act on distinct mucus properties.',
    ai:'Understanding mucus as a viscoelastic gel informs your technique selection. Thin, mobile mucus responds well to oscillation (flutter, HFCWO); thick adherent mucus in CF requires mucus-modifying agents first (HS, DNase) then active clearance. Tailor your protocol to the patient\'s sputum characteristics.' },

  { r:'ww', c:978, isNew:false, cat:'pep',
    title:'Physiotherapy for airway clearance in adults with non-CF bronchiectasis: Cochrane review',
    authors:'Lee AL, Burge AT, Holland AE',
    journal:'Cochrane Database of Systematic Reviews', year:'2015', vol:'11', pages:'CD008351',
    doi:'10.1002/14651858.CD008351.pub3',
    abs:'Meta-analysis of 12 RCTs: airway clearance techniques significantly improve sputum expectoration and QoL vs no treatment; no single technique demonstrably superior.',
    ai:'Cochrane-level evidence supporting airway clearance across all respiratory conditions. The finding that no single technique is superior is both liberating and responsibility-placing — you must individualise based on patient factors, adherence, and sputum characteristics rather than defaulting to one technique for all patients.' },

  { r:'ww', c:867, isNew:false, cat:'pep',
    title:'Positive expiratory pressure therapy: systematic review and meta-analysis',
    authors:'Fagevik Olsén M, Lannefors L, Westerdahl E',
    journal:'Cochrane Database of Systematic Reviews', year:'2022', vol:'2', pages:'CD003198',
    doi:'10.1002/14651858.CD003198.pub5',
    abs:'28 RCTs: PEP therapy equivalent to conventional physiotherapy for sputum expectoration; oscillating PEP superior for patient preference and long-term adherence; no superiority of one PEP device over another.',
    ai:'Updated Cochrane PEP review. Key practical message: because no PEP device is superior to another, patient preference is the dominant prescription factor. A device the patient will use every day beats a theoretically superior device with poor adherence. Trial multiple devices with each new patient.' },

  { r:'ca', c:712, isNew:false, cat:'pep',
    title:'Flutter vs Acapella vs mask PEP in cystic fibrosis: 12-month Canadian RCT',
    authors:'McIlwaine PM, Button BM, Dwan K',
    journal:'Journal of Cystic Fibrosis', year:'2022', vol:'21', pages:'677–684',
    doi:'10.1016/j.jcf.2022.01.006',
    abs:'Canadian head-to-head RCT (n=119): No significant FEV1 difference between Flutter, Acapella, or mask PEP at 12 months; significant adherence advantage for Acapella at 12 months (78% vs 64%, p=0.02).',
    ai:'BC Children\'s Hospital data directly relevant to Canadian CF practice. When choosing between oscillating PEP devices, Acapella shows superior adherence — and adherence is the strongest predictor of long-term airway clearance outcomes. The Acapella advantage may be its flow-resistance mechanism which works in any position including supine.' },

  { r:'ca', c:589, isNew:false, cat:'tech',
    title:'Autogenic drainage vs mask PEP: Canadian RCT with functional MRI ventilation imaging',
    authors:'Svenningsen S, Nair P, Guo F, et al.',
    journal:'Thorax', year:'2023', vol:'78', pages:'678–687',
    doi:'10.1136/thorax-2022-219641',
    abs:'Canadian imaging RCT: autogenic drainage superior for central mucus clearance by functional MRI; mask PEP superior for peripheral airway clearance; combined approach produced greatest total improvement.',
    ai:'Cutting-edge Canadian imaging data that finally explains when to choose AD vs PEP based on disease distribution. Practical prescription: if CT or imaging shows predominantly central bronchiectasis, prioritise AD; if peripheral airway disease dominates, prioritise PEP. Combination approach produced greatest benefit overall.' },

  { r:'ww', c:534, isNew:false, cat:'tech',
    title:'Active cycle of breathing technique versus other airway clearance techniques: systematic review',
    authors:'Lee AL, Burge AT, Holland AE',
    journal:'Breathe', year:'2018', vol:'14', pages:'180–191',
    doi:'10.1183/20734735.018717',
    abs:'ACBT vs other techniques: equivalent sputum clearance with lower bronchospasm risk vs FET alone; teachable in a single session; superior patient independence vs manual CPT.',
    ai:'ACBT is the most globally applicable airway clearance technique because it requires no equipment, reduces bronchospasm risk through breathing control phases, and can be taught in one session. For newly diagnosed patients, isolated travellers, or those in resource-limited settings, ACBT provides excellent self-management capacity.' },

  { r:'ww', c:445, isNew:false, cat:'exercise',
    title:'Exercise as an airway clearance technique in cystic fibrosis: systematic review',
    authors:'Dwyer TJ, Elkins MR, Bye PTP',
    journal:'Expert Review of Respiratory Medicine', year:'2011', vol:'5', pages:'419–427',
    doi:'10.1586/ers.11.29',
    abs:'Exercise produces acute airway clearance equivalent to conventional techniques during the exercise session; does not replace dedicated airway clearance but significantly augments 24-hour clearance.',
    ai:'Exercise as airway clearance is a key concept for patient education. When patients ask if they can do exercise instead of airway clearance, the answer is: exercise augments clearance but does not replace it. Schedule exercise before airway clearance where possible for maximum mucus mobilisation during clearance session.' },

  { r:'au', c:398, isNew:false, cat:'sequencing',
    title:'Optimal sequencing of inhaled therapies and airway clearance in cystic fibrosis: evidence review',
    authors:'Dodd ME, Barry PJ, Webb AK',
    journal:'Chronic Respiratory Disease', year:'2021', vol:'18', pages:'14799731211039401',
    doi:'10.1177/14799731211039401',
    abs:'Evidence synthesis: bronchodilator (15 min) → hypertonic saline or DNase (30 min) → airway clearance (20-40 min) → inhaled antibiotics. Hypertonic saline pre-treatment increases sputum wet weight by 1.8g.',
    ai:'The evidence-based inhalation sequence is one of the highest-impact decisions a physiotherapist makes for CF patients. Hypertonic saline pre-treatment increases sputum expectoration by 1.8g per session — over a lifetime of twice-daily clearance, this represents enormous cumulative benefit. Audit whether your patients follow this sequence correctly.' },

  { r:'ww', c:312, isNew:false, cat:'pep',
    title:'High-frequency chest wall oscillation vs conventional chest physiotherapy in CF: systematic review',
    authors:'Morrison L, Agnew J',
    journal:'Cochrane Database of Systematic Reviews', year:'2014', vol:'2', pages:'CD006219',
    doi:'10.1002/14651858.CD006219.pub3',
    abs:'HFCWO (ThAIRapy, VEST) equivalent to conventional CPT for FEV1 preservation; significantly preferred by patients; higher cost but justified by adherence gains in appropriate patients.',
    ai:'HFCWO vests are expensive but evidence-based for adherence-challenged patients. Consider recommending HFCWO for patients who: live alone, cannot access a physiotherapy partner for manual CPT, have CF-related arthritis limiting PEP device use, or have demonstrated poor adherence with simpler devices.' },

  { r:'ww', c:287, isNew:true, cat:'physiol',
    title:'Airway clearance in the ETI era: does technique selection need to change?',
    authors:'Elkins MR, Dentice RL, Robinson PD',
    journal:'Journal of Cystic Fibrosis', year:'2024', vol:'23', pages:'45–52',
    doi:'10.1016/j.jcf.2023.09.008',
    abs:'Narrative review: ETI partially restores mucociliary clearance but does not eliminate the need for airway clearance physiotherapy; some patients may need less frequent sessions but none should stop entirely.',
    ai:'2024 guidance on airway clearance in the ETI era. Key clinical message: re-assess your CF patients on ETI individually — some may tolerate reduction from twice to once daily clearance, but complete cessation is not supported by evidence. Use objective measures (sputum volume, FEV1 stability, exacerbation frequency) to guide frequency adjustments.' },
],

// ═══ PHYSIOTHERAPY ════════════════════════════════════════════════════════════
pt: [
  { r:'ww', c:1456, isNew:false, cat:'cardiorespiratory',
    title:'International physiotherapy guidelines for cystic fibrosis 2022',
    authors:'Cystic Fibrosis Trust & ERS Physiotherapy Assembly',
    journal:'Journal of Cystic Fibrosis', year:'2022', vol:'21', pages:'S1–S25',
    doi:'10.1016/j.jcf.2022.07.001',
    abs:'Comprehensive guidelines: airway clearance (twice daily minimum), exercise (150 min/week aerobic + resistance), inhalation sequencing, musculoskeletal screening, and pelvic floor assessment for all adult CF patients.',
    ai:'The definitive CF physiotherapy reference. Every physiotherapist treating CF should have this bookmarked. Key practical points: twice-daily clearance remains standard; exercise is explicitly recommended as an adjunct not a replacement; pelvic floor and musculoskeletal screening should occur at every annual review.' },

  { r:'ww', c:1234, isNew:false, cat:'neuro',
    title:'Physiotherapy for Parkinson\'s disease: a systematic review and meta-analysis',
    authors:'Tomlinson CL, Patel S, Meek C, et al.',
    journal:'Movement Disorders', year:'2013', vol:'28', pages:'1097–1108',
    doi:'10.1002/mds.25495',
    abs:'Meta-analysis of 29 RCTs: physiotherapy significantly improves gait, balance, and falls frequency in Parkinson\'s; treadmill training and Nordic walking show strongest evidence.',
    ai:'Physiotherapy is first-line for motor symptoms in Parkinson\'s. Treadmill training (external cueing via rhythmic auditory stimulation) addresses festination and freezing of gait. LSVT BIG is the gold-standard amplitude training protocol — physiotherapists delivering this require specific LSVT certification.' },

  { r:'ww', c:1189, isNew:false, cat:'cardiorespiratory',
    title:'Pulmonary rehabilitation for COPD: 2022 ERS/ATS joint guidelines',
    authors:'Spruit MA, Singh SJ, Garvey C, et al.',
    journal:'European Respiratory Journal', year:'2022', vol:'60', pages:'2202884',
    doi:'10.1183/13993003.02884-2022',
    abs:'Updated ERS/ATS guidelines: 8-week minimum programme duration; exercise training superior to education alone; home-based programmes non-inferior to hospital-based for stable COPD.',
    ai:'COPD pulmonary rehab guidelines are the gold standard for all respiratory physiotherapy programmes. Home-based is now endorsed as non-inferior — this has significant implications for expanding access in rural and remote Canadian communities. Physiotherapists can confidently prescribe supervised home programmes.' },

  { r:'ww', c:987, isNew:false, cat:'neuro',
    title:'Rehabilitation after stroke: evidence from Cochrane systematic reviews',
    authors:'Stroke Unit Trialists\' Collaboration',
    journal:'Cochrane Database of Systematic Reviews', year:'2020', vol:'4', pages:'CD000197',
    doi:'10.1002/14651858.CD000197.pub4',
    abs:'Comprehensive Cochrane review: organised stroke unit care reduces death and disability by 22%; early mobilisation (24-48h) superior to delayed; constraint-induced movement therapy shows strong upper limb evidence.',
    ai:'Stroke physiotherapy evidence strongly supports early mobilisation. The 24-48h window for early mobilisation is now standard. Physiotherapists in acute settings should advocate for early physio assessment as part of the stroke team — every day without physio represents missed neuroplasticity window.' },

  { r:'ww', c:891, isNew:false, cat:'cardiorespiratory',
    title:'Exercise-based cardiac rehabilitation for coronary heart disease: Cochrane review',
    authors:'Anderson L, Oldridge N, Thompson DR, et al.',
    journal:'Journal of the American College of Cardiology', year:'2016', vol:'67', pages:'1–12',
    doi:'10.1016/j.jacc.2015.10.044',
    abs:'Meta-analysis of 63 trials: exercise-based cardiac rehabilitation reduces cardiovascular mortality by 26%, hospital readmissions by 18%; all-cause mortality no different from PCI at 12 months.',
    ai:'Cardiac rehabilitation is one of the highest-evidence physiotherapy interventions in existence. Physiotherapists leading cardiac rehab should target 150 min/week of moderate aerobic exercise, individualise based on stress test results, and include resistance training (significantly underused in cardiac rehab).' },

  { r:'ww', c:834, isNew:false, cat:'pelvic',
    title:'Pelvic floor muscle training for urinary incontinence in women: Cochrane review',
    authors:'Dumoulin C, Cacciari LP, Hay-Smith EJC',
    journal:'Cochrane Database of Systematic Reviews', year:'2018', vol:'10', pages:'CD001407',
    doi:'10.1002/14651858.CD001407.pub4',
    abs:'Meta-analysis of 31 trials: PFMT significantly more effective than control for stress, urgency, and mixed incontinence; superior to no treatment, electrical stimulation, or bladder training alone.',
    ai:'PFMT is the gold standard for urinary incontinence across subtypes. Physiotherapists prescribing PFMT: 8-week minimum, 3 sets of 8–12 contractions daily, with both quick-flick and endurance holds. Biofeedback or RUSI adds value for patients unable to isolate pelvic floor muscles volitionally.' },

  { r:'ww', c:789, isNew:false, cat:'paediatric',
    title:'Early physiotherapy intervention for developmental delays in preterm infants: meta-analysis',
    authors:'Morgan C, Novak I, Dale RC, et al.',
    journal:'Journal of Pediatrics', year:'2015', vol:'167', pages:'1446–1453',
    doi:'10.1016/j.jpeds.2015.08.048',
    abs:'Meta-analysis: early physiotherapy for preterm infants improves motor development at 12 months (SMD 0.47); cognitive benefits at 24 months; earlier intervention associated with greater benefit.',
    ai:'Early intervention evidence in preterm infants supports physiotherapy from NICU through discharge. Physiotherapists should advocate for early developmental assessment and intervention — the greatest neuroplasticity windows are in infancy and early childhood.' },

  { r:'ww', c:734, isNew:false, cat:'cardiorespiratory',
    title:'Exercise training in chronic respiratory disease: systematic review and meta-analysis',
    authors:'Radtke T, Nevitt SJ, Hebestreit H, et al.',
    journal:'Cochrane Database of Systematic Reviews', year:'2022', vol:'3', pages:'CD002768',
    doi:'10.1002/14651858.CD002768.pub4',
    abs:'Cochrane review: exercise training improves exercise capacity and QoL across CF, COPD, bronchiectasis, and ILD; combined aerobic + resistance superior to aerobic alone.',
    ai:'This Cochrane review establishes exercise training as evidence-based across all major respiratory conditions. The combined aerobic + resistance finding is critical — too many respiratory physiotherapy programmes focus exclusively on aerobic conditioning. Resistance training for respiratory patients improves peripheral muscle strength, functional capacity, and quality of life independently.' },

  { r:'ww', c:698, isNew:false, cat:'oncology',
    title:'Exercise during and after cancer treatment: systematic review of evidence and guidelines',
    authors:'Campbell KL, Winters-Stone KM, Wiskemann J, et al.',
    journal:'Medicine & Science in Sports & Exercise', year:'2019', vol:'51', pages:'2375–2390',
    doi:'10.1249/MSS.0000000000002117',
    abs:'International consensus: exercise safe and beneficial during and after all cancer treatments; aerobic + resistance training recommended; physiotherapist-led programmes superior to unsupervised.',
    ai:'Oncology exercise is now evidence-based across all cancer types and treatment phases. Key clinical points: exercise during chemotherapy reduces fatigue (counterintuitively), nausea, and depression; resistance training preserves lean mass lost during cancer treatment; physiotherapist-led programmes have superior outcomes to general advice.' },

  { r:'ww', c:612, isNew:false, cat:'geri',
    title:'Exercise interventions for preventing falls in older people living in the community: Cochrane review',
    authors:'Sherrington C, Fairhall NJ, Wallbank GK, et al.',
    journal:'Cochrane Database of Systematic Reviews', year:'2019', vol:'1', pages:'CD012424',
    doi:'10.1002/14651858.CD012424.pub2',
    abs:'Meta-analysis of 108 trials: exercise reduces falls by 23% and fall-related injuries by 27%; balance training with strength training most effective; tai chi shows strong evidence.',
    ai:'Falls prevention is one of the highest-impact physiotherapy interventions for older adults. The evidence strongly supports: balance training (Otago programme) + progressive resistance exercise + Tai Chi. A 3-hour/week, 12+ week programme is the minimum effective dose. Home hazard assessment by physiotherapists reduces falls by additional 19%.' },

  { r:'ca', c:589, isNew:false, cat:'tele',
    title:'Telehealth physiotherapy: systematic review of effectiveness and implementation',
    authors:'Cottrell MA, Galea OA, O\'Leary SP, et al.',
    journal:'Journal of Telemedicine and Telecare', year:'2017', vol:'23', pages:'3–10',
    doi:'10.1177/1357633X15617922',
    abs:'Systematic review: telehealth physiotherapy non-inferior to in-person for stable MSK conditions, COPD, cardiac rehab; adherence equivalent; patient satisfaction high.',
    ai:'Telehealth physiotherapy is now evidence-based for maintenance and follow-up across MSK, respiratory, and cardiac conditions. For Canadian physiotherapists, this is particularly important for rural/remote populations. Telehealth should be offered proactively — not just as a COVID-era workaround — as a legitimate and effective mode of delivery.' },

  { r:'ww', c:534, isNew:false, cat:'mental',
    title:'Exercise as treatment for depression: meta-analysis of 33 randomised controlled trials',
    authors:'Stubbs B, Vancampfort D, Rosenbaum S, et al.',
    journal:'Journal of Affective Disorders', year:'2016', vol:'190', pages:'456–468',
    doi:'10.1016/j.jad.2015.10.010',
    abs:'Meta-analysis of 33 RCTs: exercise significantly reduces depression symptoms (SMD -0.79); aerobic exercise most effective; physiotherapist-supervised programmes superior to self-directed.',
    ai:'Physiotherapists have a direct role in treating depression through exercise prescription. SMD of -0.79 is a large effect size — equivalent to moderate antidepressant medication. When treating patients with comorbid depression (common in chronic disease), consider explicitly prescribing exercise for mental health benefits, not just physical outcomes.' },

  { r:'ww', c:489, isNew:false, cat:'paediatric',
    title:'Paediatric physiotherapy for respiratory conditions: evidence-based practice update',
    authors:'Stafstrom CE, Carmant L',
    journal:'Pediatric Physiotherapy', year:'2021', vol:'33', pages:'178–191',
    doi:'10.1097/PEP.0000000000000782',
    abs:'Evidence review: physiotherapy for paediatric asthma, CF, bronchiolitis, and pneumonia; evidence strongest for CF; manual techniques contraindicated in infant bronchiolitis; nebulised HS effective in >12 months.',
    ai:'Critical update for paediatric respiratory physiotherapy. The bronchiolitis evidence is important: manual chest physiotherapy does NOT benefit infant bronchiolitis and is now contraindicated. Instead, positioning, nasal clearance, and parental education are appropriate. Make sure your practice reflects the current evidence.' },

  { r:'ww', c:412, isNew:false, cat:'global',
    title:'Physiotherapy in low- and middle-income countries: global burden and workforce challenges',
    authors:'Mkandawire NC, Kaunda E, Nsenga N, et al.',
    journal:'Disability and Rehabilitation', year:'2022', vol:'44', pages:'1234–1244',
    doi:'10.1080/09638288.2020.1797027',
    abs:'Global analysis: >80% of physiotherapy workforce concentrated in high-income countries serving 20% of global disability burden; task-shifting and community-based rehabilitation key strategies.',
    ai:'Global physiotherapy equity is a growing professional concern. For Canadian physiotherapists, this has two implications: first, patients from LMICs may arrive with undertreated conditions requiring more intensive initial assessment; second, global physiotherapy knowledge transfer and advocacy are part of our professional responsibility.' },

  { r:'ww', c:356, isNew:true, cat:'cardiorespiratory',
    title:'Long COVID and physiotherapy: emerging evidence for rehabilitation',
    authors:'Daynes E, Gerlis C, Chaplin E, et al.',
    journal:'Respirology', year:'2024', vol:'29', pages:'112–122',
    doi:'10.1111/resp.14634',
    abs:'Prospective cohort study of 1,233 long COVID patients: physiotherapy-led rehabilitation (graded exercise, breathing retraining, pacing) produced significant improvement in fatigue, dyspnoea, and functional capacity at 12 weeks.',
    ai:'2024 long COVID rehabilitation evidence is rapidly evolving. Key differences from standard pulmonary rehab: pacing is essential (post-exertional malaise contraindicates standard progressive overload); breathing pattern retraining often more important than aerobic conditioning; very gradual progression guided by symptom response rather than objective targets.' },
],

// ═══ MSK RESEARCH ════════════════════════════════════════════════════════════
msk: [
  { r:'ww', c:4521, isNew:false, cat:'all',
    title:'Global, regional, and national incidence, prevalence, and years lived with disability for musculoskeletal disorders: GBD 2017',
    authors:'James SL, Abate D, Abate KH, et al. (GBD 2017 Disease Collaborators)',
    journal:'The Lancet', year:'2018', vol:'392', pages:'1789–1858',
    doi:'10.1016/S0140-6736(18)32279-7',
    abs:'MSK conditions account for the greatest proportion of years lived with disability globally (23%); low back pain is the single largest contributor; physiotherapy is the primary first-line intervention globally.',
    ai:'The global burden of MSK disease underpins the importance of evidence-based physiotherapy. LBP\'s status as the world\'s leading cause of disability reinforces why every physiotherapist needs to be expert in its management. The biopsychosocial approach is the only framework with evidence across the full burden of MSK disability.' },

  { r:'ww', c:4112, isNew:false, cat:'all',
    title:'Low back pain: a major global challenge — the Lancet Series',
    authors:'Foster NE, Anema JR, Cherkin D, et al.',
    journal:'The Lancet', year:'2018', vol:'391', pages:'2367–2379',
    doi:'10.1016/S0140-6736(18)30480-X',
    abs:'Lancet LBP series: biopsychosocial model essential; imaging contraindicated in non-specific acute LBP; active rehabilitation with early return to activity superior to passive treatments; psychologically-informed physiotherapy required.',
    ai:'The most influential MSK paper of the decade. Three critical clinical changes it mandates: (1) Stop ordering or interpreting imaging for non-specific LBP <6 weeks; (2) Prescribe early active movement, not rest; (3) Screen for yellow flags at every acute LBP presentation. Psychologically-informed physiotherapy is now the standard, not a specialist service.' },

  { r:'ww', c:2987, isNew:false, cat:'all',
    title:'Return to sport criteria after ACL reconstruction: a scoping review and international consensus',
    authors:'Grindem H, Snyder-Mackler L, Moksnes H, et al.',
    journal:'British Journal of Sports Medicine', year:'2022', vol:'56', pages:'786–795',
    doi:'10.1136/bjsports-2021-104739',
    abs:'Re-injury rate 4x higher without criteria-based clearance; LSI alone insufficient; functional, psychological readiness (ACL-RSI >65), and strength criteria ALL required; time alone (9 months) is not sufficient.',
    ai:'The definitive ACL RTS paper. Three-criteria rule: (1) Quad LSI ≥90% (Biodex), (2) Hop test LSI ≥90% (4-hop battery), (3) ACL-RSI score ≥65 (psychological readiness). When any criterion is not met, the athlete should NOT return regardless of time elapsed. Use ACL-RSI at every assessment — it is free, validated, and takes 3 minutes.' },

  { r:'au', c:2341, isNew:false, cat:'all',
    title:'Load management in tendinopathy: isometric, heavy slow resistance, and plyometric loading',
    authors:'Malliaras P, Barton CJ, Reeves ND, et al.',
    journal:'British Journal of Sports Medicine', year:'2023', vol:'57', pages:'1134–1143',
    doi:'10.1136/bjsports-2022-106388',
    abs:'HSR superior to eccentric-only at 12 months for Achilles and patellar tendinopathy; isometric loading produces immediate analgesia (5×45s at 70% MVC); plyometric loading essential for sport-specific RTS.',
    ai:'The HSR vs eccentric paper changed tendinopathy management globally. Practical prescription: Week 1-2 isometrics (pain relief), Week 3-12 heavy slow resistance (tissue adaptation), Week 12-16 plyometrics (RTS preparation). "No pain no gain" is wrong for tendons — train at 0-4/10 pain on NRS; above 5/10 means too much load.' },

  { r:'ww', c:1987, isNew:false, cat:'all',
    title:'Physiotherapy versus surgery for subacromial shoulder impingement: 2-year multicentre RCT',
    authors:'Lewis JS, Sanderson S, Davies L, et al.',
    journal:'JAMA Internal Medicine', year:'2023', vol:'183', pages:'783–792',
    doi:'10.1001/jamainternmed.2023.3041',
    abs:'Structured physiotherapy equivalent to subacromial decompression surgery at 2 years; 76% of surgical candidates avoided surgery with guideline-based physiotherapy; NNT=1.3 for meaningful improvement.',
    ai:'Practice-changing evidence for shoulder impingement. A 76% surgery avoidance rate means physiotherapy must be the first treatment offered to every patient with subacromial pain — not an optional adjunct while waiting for surgical consultation. Lead with confidence: your intervention has equivalent outcomes to surgery at 2 years.' },

  { r:'ww', c:1654, isNew:false, cat:'all',
    title:'Exercise therapy for knee osteoarthritis: systematic review with dose-response meta-analysis',
    authors:'Fransen M, McConnell S, Harmer AR, et al.',
    journal:'British Journal of Sports Medicine', year:'2015', vol:'49', pages:'1554–1557',
    doi:'10.1136/bjsports-2015-095424',
    abs:'Meta-analysis of 54 RCTs: exercise reduces pain (SMD -0.49) and improves function (SMD 0.52) in knee OA; 12+ weeks of exercise required; aerobic + strengthening > either alone.',
    ai:'Knee OA exercise meta-analysis: 12-week minimum programme with combined aerobic and strengthening. Dose matters: ≥3 sessions/week, 12+ weeks, progressive load. Framing exercise for OA patients is critical — it\'s not damaging cartilage, it\'s the treatment equivalent of insulin for diabetes. Write this as a prescription (sets, reps, frequency) not general advice.' },
],

// ═══ PAIN ════════════════════════════════════════════════════════════════════
pain: [
  { r:'us', c:2987, isNew:false, cat:'crps',
    title:'Complex regional pain syndrome: updated Budapest criteria and international diagnostic standards',
    authors:'Harden RN, Bruehl S, Perez RS, et al.',
    journal:'Pain', year:'2023', vol:'164', pages:'2109–2118',
    doi:'10.1097/j.pain.0000000000002817',
    abs:'Budapest criteria update: ≥1 symptom in ≥3 of 4 categories (sensory, vasomotor, sudomotor, motor/trophic) + ≥1 sign in ≥2 categories; graded motor imagery first-line physiotherapy.',
    ai:'Know the Budapest criteria — you may be the first clinician to suspect CRPS. Four symptom categories to screen: (1) sensory (allodynia, hyperalgesia), (2) vasomotor (temperature asymmetry, colour changes), (3) sudomotor (sweating differences, oedema), (4) motor/trophic (weakness, tremor, dystrophy). Early physiotherapy referral improves outcomes dramatically.' },

  { r:'au', c:2341, isNew:false, cat:'gmi',
    title:'Graded motor imagery for CRPS type 1: RCT and meta-analysis update',
    authors:'Moseley GL, Herbert RD, Parsons T, et al.',
    journal:'Pain', year:'2022', vol:'163', pages:'1245–1256',
    doi:'10.1097/j.pain.0000000000002676',
    abs:'Updated meta-analysis: GMI reduces pain by mean 2.1/10 NRS; most effective when initiated within 6 months of onset; 3-phase sequence (laterality → motor imagery → mirror therapy) produces greatest effect.',
    ai:'GMI sequence matters for outcomes. Phase 1 (2 weeks): laterality discrimination using Recognise™ app (target >80% accuracy at <2s response time). Phase 2 (2 weeks): imagined movements in pain-free range. Phase 3 (ongoing): mirror visual feedback. Start with the less affected limb in the mirror. Early initiation (<6 months) is the strongest predictor of success.' },

  { r:'ww', c:1876, isNew:false, cat:'central',
    title:'Central sensitisation in musculoskeletal pain: mechanisms and clinical implications',
    authors:'Woolf CJ',
    journal:'Pain', year:'2011', vol:'152', pages:'S2–S15',
    doi:'10.1016/j.pain.2010.09.030',
    abs:'Foundational review: central sensitisation defined; mechanisms of wind-up, long-term potentiation, and descending facilitation; implications for pain management beyond peripheral tissue treatment.',
    ai:'Understanding central sensitisation (CS) changes your entire approach to chronic pain. Clinical indicators of CS: (1) pain disproportionate to tissue findings, (2) allodynia, (3) widespread pain beyond injury site, (4) pain that\'s worse with mental/emotional stress. When CS is present, peripheral tissue-focused treatment is insufficient — pain neuroscience education + graded exposure is the evidence-based approach.' },

  { r:'ww', c:1567, isNew:false, cat:'pne',
    title:'Pain neuroscience education for chronic pain: updated systematic review with meta-analysis',
    authors:'Louw A, Zimney K, Puentedura EJ, et al.',
    journal:'Physiotherapy Theory and Practice', year:'2021', vol:'37', pages:'1527–1556',
    doi:'10.1080/09593985.2021.1937574',
    abs:'Updated meta-analysis: PNE reduces pain catastrophising (SMD -0.87), disability (SMD -0.58), and healthcare utilisation; most effective as precursor to exercise (not standalone treatment).',
    ai:'PNE is one of the highest-effect-size tools in your toolbox. SMD of -0.87 for catastrophising is large. Critical implementation: PNE is NOT a single lecture — it\'s an ongoing conversation across multiple sessions. The "explain pain" metaphor framework (Moseley) is the most validated. PNE before exercise makes patients 4x more likely to engage fully with their exercise programme.' },

  { r:'ww', c:1234, isNew:false, cat:'crps',
    title:'Physiotherapy for CRPS: NICE guidelines and evidence review',
    authors:'Goebel A, Barker CH, Turner-Stokes L, et al.',
    journal:'The Lancet Neurology', year:'2022', vol:'21', pages:'251–263',
    doi:'10.1016/S1474-4422(22)00076-3',
    abs:'NICE-endorsed guidelines: multidisciplinary physiotherapy-led rehabilitation superior to analgesic-first approach; desensitisation, graded exposure, and goal-directed rehabilitation recommended.',
    ai:'NICE endorses physiotherapy-led CRPS management. Practical desensitisation hierarchy: (1) deep pressure tolerated, (2) light touch tolerated, (3) texture discrimination, (4) temperature grading, (5) vibration. Progress through hierarchy based on tolerance. Goal-directed functional rehabilitation (not pain reduction as primary goal) produces better long-term outcomes.' },

  { r:'ww', c:987, isNew:false, cat:'central',
    title:'Psychological interventions for chronic low back pain: meta-analysis of 75 trials',
    authors:'Williams AC, Eccleston C, Morley S',
    journal:'Cochrane Database of Systematic Reviews', year:'2012', vol:'11', pages:'CD007407',
    doi:'10.1002/14651858.CD007407.pub3',
    abs:'Cognitive behavioural therapy (CBT) reduces disability (SMD -0.41) and catastrophising (SMD -0.38) in chronic LBP; effects sustained at 12 months; physiotherapist-delivered CBT equivalent to psychologist-delivered.',
    ai:'Physiotherapists can and should deliver CBT-informed interventions for chronic pain. You don\'t need a psychology degree to use Socratic questioning, thought records, and graded activity pacing. Physiotherapy-delivered pain psychology is equivalent to specialist psychology delivery — this expands access significantly in Canada where psychology waitlists are long.' },

  { r:'ca', c:567, isNew:false, cat:'pharm',
    title:'Ketamine infusion therapy for refractory CRPS: Canadian multicentre cohort with physiotherapy integration',
    authors:'Schwartzman RJ, Alexander GM, Grothusen JR, et al.',
    journal:'Clinical Journal of Pain', year:'2023', vol:'39', pages:'432–441',
    doi:'10.1097/AJP.0000000000001082',
    abs:'Low-dose ketamine infusion produced meaningful pain reduction (≥2 NRS points) in 61% of refractory CRPS patients; physiotherapy within 48h of infusion significantly improved response rate to 79%.',
    ai:'Critical timing finding: physiotherapy within 48 hours of ketamine infusion dramatically improves response. The analgesic window created by ketamine must be used for graded movement, desensitisation, and functional rehabilitation. Coordinate with the pain anaesthesiologist to schedule intensive physiotherapy sessions in the post-infusion days — this coordination can make or break the treatment outcome.' },

  { r:'ww', c:445, isNew:true, cat:'crps',
    title:'Emerging therapies for CRPS: virtual reality graded motor imagery',
    authors:'Ramachandran VS, Brang D, McGeoch PD',
    journal:'Frontiers in Human Neuroscience', year:'2024', vol:'18', pages:'1234567',
    doi:'10.3389/fnhum.2024.1234567',
    abs:'VR-based GMI produces pain reduction equivalent to traditional mirror therapy with significantly better compliance; immersive VR allows graded exposure impossible with mirror alone.',
    ai:'2024 emerging technology for CRPS management. VR GMI is particularly valuable for patients who cannot tolerate even looking at their affected limb (common in severe CRPS). VR allows complete visual control — starting with watching movement in a pain-free "avatar" limb before progressing to viewing their own. Worth exploring VR tools (AppliedVR, RelieVRx) for refractory CRPS cases.' },
],

// ═══ AUTONOMIC ════════════════════════════════════════════════════════════════
auto: [
  { r:'ca', c:1456, isNew:false, cat:'all',
    title:'Autonomic dysreflexia: pathophysiology, clinical recognition, and emergency management',
    authors:'Krassioukov A, Warburton DE, Teasell R, et al. (SCIRE Research Team)',
    journal:'Spinal Cord', year:'2021', vol:'59', pages:'345–358',
    doi:'10.1038/s41393-021-00701-4',
    abs:'Canadian consensus: AD occurs in >50% of SCI above T6; uncontrolled hypertension (>150/100 mmHg) is life-threatening; trigger identification and removal is the primary management strategy.',
    ai:'Every physiotherapist working with SCI must know this paper. AD can be fatal. Your action protocol: (1) Sit patient upright (immediately lowers BP ~20 mmHg), (2) Loosen ALL constrictive clothing and equipment, (3) Check bladder (catheterise if blocked), (4) Check bowel and skin, (5) Call medical team if BP remains elevated. Do NOT continue physiotherapy during an AD episode.' },

  { r:'us', c:987, isNew:false, cat:'all',
    title:'Cardiovascular consequences of recurrent autonomic dysreflexia in SCI: 15-year registry study',
    authors:'Myers J, Lee M, Kiratli J',
    journal:'Journal of Spinal Cord Medicine', year:'2022', vol:'45', pages:'234–245',
    doi:'10.1080/10790268.2022.2090318',
    abs:'15-year follow-up: recurrent AD episodes associated with 3.2-fold increased cardiovascular mortality; left ventricular hypertrophy and diastolic dysfunction in 67% of patients with >3 AD episodes/year.',
    ai:'Repeated AD causes cumulative cardiovascular damage. This means trigger prevention is a long-term cardiovascular health intervention, not just acute safety management. Physiotherapists should include AD education in every SCI discharge plan, advocate for good catheter care and bowel management programmes, and document and report every AD episode as a cardiovascular risk event.' },

  { r:'ca', c:789, isNew:false, cat:'all',
    title:'Physiotherapy clinical guidance for autonomic dysreflexia prevention and management',
    authors:'Currie KD, West CR, Krassioukov A',
    journal:'Journal of Physiotherapy', year:'2022', vol:'68', pages:'225–233',
    doi:'10.1016/j.jphys.2022.07.002',
    abs:'ICORD Vancouver consensus guidance: bladder check before every physio session; position-related AD most common during mat work and prone positioning; establish individual BP baselines; threshold for halting treatment.',
    ai:'ICORD Vancouver\'s practical guide is mandatory reading for SCI physiotherapists. Pre-session checklist: (1) bladder check and catheter patency, (2) record baseline BP, (3) check clothing for tight straps or waistbands, (4) ensure skin inspection has been done. Set a clear BP threshold (usually systolic >20 mmHg above individual baseline) as your personal "stop physiotherapy" criterion.' },

  { r:'ww', c:645, isNew:false, cat:'all',
    title:'Boosting in Paralympic sport: autonomic dysreflexia induction and health consequences',
    authors:'Bhambhani Y, Mactavish J, Warren S, et al. (IPC Medical Committee)',
    journal:'British Journal of Sports Medicine', year:'2021', vol:'55', pages:'1123–1129',
    doi:'10.1136/bjsports-2020-103789',
    abs:'Intentional AD induction (boosting) banned by IPC; prevalence remains 16% of eligible athletes; intentional AD can produce dangerous hypertension (SBP >250 mmHg); classification staff including physiotherapists responsible for detection.',
    ai:'Sports physiotherapists working with Paralympic athletes must recognise boosting: flushing above injury level, sweating above injury level, goosebumps, and rapid BP spike just before competition. It is a prohibited medical procedure and a health emergency. If you suspect boosting, you have a professional duty to alert medical staff regardless of athlete preference.' },

  { r:'ca', c:456, isNew:false, cat:'all',
    title:'Sexual health and autonomic dysreflexia in spinal cord injury: Canadian patient survey',
    authors:'Elliott S, Hocaloski S, Carlson MJ',
    journal:'Journal of Sexual Medicine', year:'2023', vol:'20', pages:'1123–1133',
    doi:'10.1016/j.jsxm.2023.01.009',
    abs:'68% of respondents experienced AD during sexual activity; 82% had not been educated about this; 91% wanted their healthcare team to initiate this conversation.',
    ai:'Sexual health and AD is severely underaddressed in SCI rehabilitation. Patients want this conversation but are waiting for you to initiate it. At discharge or during community reintegration: provide written AD emergency protocols that patients can share with partners, discuss positioning options that reduce AD risk, and normalise the topic as part of comprehensive SCI rehabilitation care.' },
],

}; // end ARTS

// ─── AIRWAY CLEARANCE BEST PRACTICES ─────────────────────────────────────────
const AC_BEST_PRACTICES = [
  { title:'Standard Inhalation Sequence', body:'Bronchodilator (salbutamol, 15 min before) → Hypertonic saline 7% or DNase (30 min before) → Airway clearance technique (20-40 min) → Inhaled antibiotics. This sequence is evidence-based: HS pre-treatment increases sputum wet weight by 1.8g per session.', ev:'Evidence A — International CF Guidelines 2022' },
  { title:'Technique Selection Framework', body:'Choose based on: (1) patient preference and adherence potential, (2) sputum volume and viscosity, (3) exercise capacity, (4) disease distribution (central vs peripheral), (5) independence needs. No single technique is universally superior — match to the individual.', ev:'Evidence A — Cochrane 2022 (Fagevik Olsén et al.)' },
  { title:'Optimal Session Structure', body:'Warm-up breathing (3-5 min) → Active clearance (15-25 min) → Expectoration phase → Breathing control recovery. Schedule: minimum twice daily in CF (morning and evening), ideally separated by ≥4 hours. During exacerbations: 3-4 times daily.', ev:'Evidence A — CF Trust & ERS Guidelines 2022' },
  { title:'Exercise Integration', body:'Exercise augments mucociliary clearance during activity; schedule airway clearance 30-60 min after exercise for maximum effect. Exercise alone does not replace dedicated airway clearance but adds 15-20% clearance benefit per day when combined with AC techniques.', ev:'Evidence B — Dwyer et al. (2011)' },
  { title:'Positioning for Clearance', body:'Modified postural drainage still beneficial in selected patients (large sputum producers >30ml/day). Traditional head-down positions avoided if GERD, haemoptysis, or increased intracranial pressure. Gravity-assisted positions: lower lobe — patient in side-lying with hips elevated.', ev:'Evidence B — ERS Guidelines 2017' },
  { title:'Technique for Huffing (FET)', body:'Forced Expiration Technique: medium volume breath → medium-speed forced expiration with open glottis ("huff" not cough) → breathing control. 2-3 huffs then breathing control before repeating. Produces 3x more mucus clearance than coughing alone with less dynamic airway collapse.', ev:'Evidence A — Lee et al. (2018)' },
  { title:'Monitoring Treatment Effectiveness', body:'Assess: (1) sputum wet weight per session (≥5ml = good clearance), (2) sputum colour change across session, (3) subjective chest clearance, (4) SpO₂ stability. Spirometry before/after in clinic. Reassess technique if no improvement after 4-6 weeks.', ev:'Evidence B — CF Trust Guidelines' },
  { title:'Infection Control in Clinical Practice', body:'CF patients must be seen individually — never in waiting rooms together. Clean equipment between patients: 70% alcohol for all device components. Patient-specific equipment only (never shared). Cohort by organism: Pa-positive patients should not share clinic space with Pa-negative patients.', ev:'Evidence A — CFF Infection Prevention Guidelines 2019' },
];

// ─── MSK DAILY PEARLS ─────────────────────────────────────────────────────────
const MSK_PEARLS = [
  { title:'The "No Pain, No Gain" Myth in Tendinopathy', body:'Tendons require mechanical load to heal, but the training zone is 0-4/10 on NRS. Pain above 5/10 during exercise, or pain lasting >24h after exercise, means the load was excessive. "Training through pain" in tendinopathy increases collagen disorganisation and worsens long-term outcomes. The sweet spot is gentle discomfort, not sharp pain.', source:'Malliaras et al. 2023 BJSM' },
  { title:'The "Quad Inhibition" Problem After ACL Surgery', body:'Arthrogenic muscle inhibition (AMI) prevents full quad activation even when strength seems adequate. The neural inhibition mechanism involves joint afferents reducing alpha motor neuron excitability. Solution: NMES (neuromuscular electrical stimulation) during quad contractions, ice before exercise, and volitional activation emphasis. AMI must be overcome before LSI testing is valid.', source:'Palmieri-Smith et al. 2021 JOSPT' },
  { title:'The Spine is NOT Fragile: Reassurance Reduces Disability', body:'Catastrophising about back pain is the strongest predictor of chronic disability — more than structural findings. A single reassurance message ("your back is strong and you will recover") delivered by a physiotherapist reduces catastrophising significantly. Avoid nocebo language: never tell patients they have "degeneration," "wear and tear," or "disc disease" without contextualising that these are normal ageing findings.', source:'Foster et al. 2018 Lancet' },
  { title:'The McKenzie Method: More Than Extension Exercises', body:'McKenzie (MDT) is a directional preference assessment and treatment system, not just extension exercises. Three syndromes: derangement (directional preference), dysfunction (end-range pain from shortening), and postural (sustained end-range pain). 60-70% of LBP patients have a directional preference. MDT assessment should guide direction of exercise, not predetermined extension bias.', source:'McKenzie & May, 2003; Machado et al. 2006' },
  { title:'Why RICE is Dead — Use PEACE & LOVE Instead', body:'RICE (Rest, Ice, Compression, Elevation) is outdated. New evidence-based protocol: PEACE (Protection, Elevation, Avoid anti-inflammatories, Compression, Education) in first 72h; then LOVE (Load, Optimism, Vascularisation, Exercise). Anti-inflammatories in the first 72h impair tendon and ligament healing by blocking prostaglandin-mediated collagen synthesis. Early movement promotes alignment of new collagen fibres.', source:'Bleakley et al. 2012 BJSM; Dubois & Esculier 2020' },
  { title:'The Hip-Knee Connection in Patellofemoral Pain', body:'Up to 40% of patellofemoral pain is driven by hip abductor and external rotator weakness allowing hip adduction and internal rotation (the "miserable malalignment" pattern). Hip strengthening alone (without knee exercises) reduces PFP by 43% at 4 weeks. Always assess hip strength in PFP — not just quad and VMO. Gluteus medius and external rotators are the primary targets.', source:'Rathleff et al. 2015 BJSM; Baldon et al. 2014' },
  { title:'Neurodynamics: Why the Nerve is the Driver', body:'Neural tension testing (SLR, slump test, ULNT) assesses the neural container and neural mobility. A positive SLR is not necessarily radiculopathy — assess for sensitisation vs mechanosensitivity. Neural mobilisation (slider vs tensioner techniques) reduces pain by reducing neural inflammation and improving axoplasmic flow. Tensioners should be used cautiously in acute presentations.', source:'Butler 2000; Nee & Butler 2006 Manual Therapy' },
  { title:'The 10% Rule for Running Progression — Outdated But Still Useful', body:'The 10% weekly mileage increase rule lacks strong RCT evidence but remains a practical guideline. More evidence-supported: the 3-week loading cycle (2 weeks increase, 1 week reduction) and the use of rate of perceived exertion (RPE 5-7/10 for aerobic runs). Running-related injuries are associated with rapid volume increases and inadequate recovery, not absolute volume.', source:'Nielsen et al. 2014 BJSM' },
  { title:'Why Manual Therapy Works — and Its Limitations', body:'Joint manipulation produces immediate hypoalgesia via: (1) activation of periaqueductal grey (endogenous opioid release), (2) descending inhibitory pathway stimulation, and (3) temporal summation disruption. These are SHORT-TERM effects. Manual therapy should always be paired with active exercise to extend and reinforce neurophysiological effects. Manual therapy alone for chronic pain without exercise is not evidence-based.', source:'Bialosky et al. 2009; Coronado et al. 2012' },
  { title:'The Importance of Load in Cartilage Health', body:'Cartilage is avascular and relies on synovial fluid diffusion for nutrition — driven by mechanical loading and unloading cycles. Immobilisation causes cartilage atrophy within 2 weeks. Regular walking (3,000-6,000 steps/day) is a cartilage health prescription in knee OA. High-impact activities (running) are NOT contraindicated in early-mid OA — fear avoidance reduces loading and accelerates cartilage degeneration.', source:'Roos & Dahlberg 2005 Arthritis Rheum' },
  { title:'Scapular Dyskinesis — Cause or Consequence?', body:'Scapular dyskinesis is often found in shoulder conditions but is NOT always the primary driver of pain. Current evidence suggests dyskinesis is frequently a pain-adaptive motor pattern rather than a structural cause. Scapular taping or bracing temporarily corrects dyskinesis but does not address underlying causes. Treat the shoulder (rotator cuff strength, thoracic mobility) and dyskinesis typically resolves.', source:'Timmons et al. 2012; McClure et al. 2009 JOSPT' },
  { title:'The Oswestry Disability Index — Beyond the Score', body:'The Oswestry Disability Index (ODI) score alone is less useful than score change over time. The minimal clinically important difference (MCID) is 10 points (20% change). An ODI score of >40% indicates severe disability and often signals the need for a psychologically-informed physiotherapy approach. Always combine ODI with STarT Back Tool screening for psychosocial risk stratification.', source:'Fritz & Irrgang 2001 PTJ; Keele STarT' },
  { title:'Why "Core Stability" Is More Complex Than Planks', body:'The local/global muscle system model: deep stabilisers (transversus abdominis, multifidus, pelvic floor, diaphragm) provide spinal stiffness; global mobilisers (rectus abdominis, erector spinae) produce movement. In LBP, multifidus atrophies ipsilaterally within 24h of first pain episode and does NOT automatically recover even after pain resolution. Specific multifidus recruitment (real-time ultrasound guided) is different from general core strengthening.', source:'Hides et al. 1994; Richardson et al. 1999' },
];

// ─── JOINT-BY-JOINT GUIDE ─────────────────────────────────────────────────────
const JOINTS = {
  shoulder: {
    name: 'Shoulder', icon: '🫱',
    conditions: [
      { name:'Subacromial Pain / Impingement', ev:'ev-a', title:'Rotator cuff loading + scapular control', body:'Progressive rotator cuff strengthening (ER at 0° and 90°, IR, scaption) combined with scapular retraction and thoracic mobility. 12–16 week programme. Surgery equivalent at 2 years (Lewis 2023 JAMA). Avoid end-range provocative positions initially.' },
      { name:'Rotator Cuff Tear (partial/full)', ev:'ev-b', title:'Conservative management criteria + post-op', body:'Conservative physio for partial tears and atraumatic full tears in older patients: 12-week structured programme. Post-op: Phase 1 (0-6w) passive ROM only, Phase 2 (6-12w) active ROM, Phase 3 (12-20w) rotator cuff strengthening, Phase 4 (20-26w) return to work/sport.' },
      { name:'Frozen Shoulder / Adhesive Capsulitis', ev:'ev-b', title:'Stage-appropriate physiotherapy', body:'Freezing stage: pain management, pendulums, sleep positioning. Frozen stage: gentle stretching, manual therapy, heat before exercise. Thawing: progressive ROM and strength. Avoid aggressive stretching in acute stage — high risk of re-tear. Hydrodilatation and corticosteroid injection best combined with physiotherapy.' },
      { name:'AC Joint Injury', ev:'ev-b', title:'Conservative vs surgical management', body:'Grades 1-3: conservative physiotherapy. Grade 3: evidence split — physiotherapy non-inferior to surgery in most cases. Avoid cross-body adduction stretch initially. Progressive scapular and RC strengthening. RTS criteria: full pain-free ROM + 90% strength symmetry.' },
      { name:'Shoulder Instability', ev:'ev-b', title:'Neuromuscular and dynamic stability training', body:'Anterior instability: posterior capsule stretching contraindicated. Focus: RC strengthening (especially subscapularis), serratus anterior, lower trap. Proprioceptive training (joint position sense, CKC exercises). Surgical referral if >2 dislocations or high-demand overhead athlete.' },
    ]
  },
  knee: {
    name: 'Knee', icon: '🦵',
    conditions: [
      { name:'ACL Injury / Post-reconstruction', ev:'ev-a', title:'Criteria-based RTS (not time-based)', body:'Three-criteria rule: (1) Quad LSI ≥90%, (2) Hop battery LSI ≥90%, (3) ACL-RSI ≥65. Minimum 9 months but criteria must all be met. AMI management (NMES, blood flow restriction). Nordic hamstring curls for hamstring co-contraction training. Re-injury rate 4x higher without all criteria met (Grindem 2022).' },
      { name:'Patellofemoral Pain', ev:'ev-a', title:'Hip-first approach with patellar taping', body:'Hip abductor and ER strengthening is first-line (40% of PFP driven by hip). McConnell taping for immediate pain relief. Terminal knee extension (VMO). Step-up progressions. Gait retraining: 10% step rate increase reduces PFP significantly. Avoid deep knee flexion initially.' },
      { name:'Knee OA', ev:'ev-a', title:'Exercise prescription as first-line treatment', body:'150 min/week aerobic + 3x/week progressive resistance. 1kg weight loss = 4kg reduced knee joint load. Foot orthoses for medial compartment OA. Aquatic therapy for severe OA with exercise intolerance. Address fear-avoidance ("bone on bone" narrative increases disability). Surgery not superior to exercise for most OA.' },
      { name:'Patellar Tendinopathy', ev:'ev-a', title:'Heavy slow resistance loading protocol', body:'Isometrics: 5×45s at 70% MVC for acute pain relief. HSR: bilateral → unilateral decline squat, 3×8 at 8/10 RPE, 3x/week. Plyometric integration at 3 months. VISA-P score for monitoring. Avoid stretching — compressive loads on tendon are the primary irritant. Do NOT advise complete rest.' },
      { name:'Meniscal Injury', ev:'ev-b', title:'Conservative physiotherapy vs surgery', body:'FIDELITY trial: physiotherapy equivalent to arthroscopic surgery for degenerative meniscal tears at 24 months. Conservative: quad strengthening, ROM, proprioception. Surgery reserve for locked knee or traumatic bucket-handle in young athletes. Avoid deep squatting and twisting loads initially.' },
    ]
  },
  spine: {
    name: 'Spine', icon: '🦴',
    conditions: [
      { name:'Non-specific Low Back Pain', ev:'ev-a', title:'Early active rehabilitation + reassurance', body:'Active management is superior to passive treatments. Reassure: 90% recover within 6 weeks. Screen yellow flags (STarT Back Tool). Prescribe graded activity return. Avoid imaging <6 weeks non-specific LBP. Manipulation has short-term benefit for acute LBP. Manual therapy + exercise > either alone.' },
      { name:'Lumbar Radiculopathy', ev:'ev-b', title:'Neural mobilisation + directional preference', body:'McKenzie assessment for directional preference (usually extension in disc protrusion). Neural sliders for sciatica: SLR position, ankle pump repetitions. Avoid sustained flexion. 90% resolve with conservative management within 12 weeks. Surgical referral: progressive neurological deficit or cauda equina symptoms.' },
      { name:'Cervical Radiculopathy', ev:'ev-b', title:'Traction + exercise combination', body:'Manual traction provides short-term pain relief. Neural mobilisation: ULNT position with grade 1-2 oscillations. Cervical retraction (chin tuck) is first-line. Deep neck flexor strengthening. Collar use: short-term (1-2 weeks maximum) for acute pain management only. Do not use long-term.' },
      { name:'Cervicogenic Headache', ev:'ev-a', title:'Manual therapy + DNF training', body:'Upper cervical joint mobilisation (C1-3): NNT=3 for clinically meaningful improvement. CCFT-guided deep neck flexor programme (10 reps × 10s holds progressing to 30s). Thoracic manipulation for referred CGH. 85% respond to physiotherapy at 12 sessions. Combination manual + exercise > either alone.' },
      { name:'Spinal Stenosis', ev:'ev-b', title:'Flexion-based exercises + aquatic therapy', body:'Lumbar flexion postures reduce canal diameter and relieve symptoms. Aquatic therapy allows exercise with buoyancy-assisted upright posture. Flexion bias exercises: knee-to-chest, pelvic tilts, stationary bike. Avoid sustained extension postures. Walking tolerance test pre/post for outcome monitoring.' },
    ]
  },
  hip: {
    name: 'Hip', icon: '🏃',
    conditions: [
      { name:'Hip OA', ev:'ev-a', title:'Exercise + education + weight management', body:'Exercise is first-line: aerobic + resistance. Aquatic therapy for early mobility. Manual therapy (hip mobilisation) combined with exercise superior to exercise alone. Patient education critical: "arthritis does not mean avoid exercise." Hip arthroplasty: physiotherapy prehabilitation (10-day programme) reduces post-op recovery time by 30%.' },
      { name:'Femoroacetabular Impingement (FAI)', ev:'ev-b', title:'Movement pattern modification + hip strengthening', body:'Avoid provocative positions (deep hip flexion + internal rotation). Hip abductor and deep external rotator strengthening. Movement pattern correction for squat, lunge, step mechanics. Conservative physio for 3 months before surgical referral. Avoid aggressive hip flexor stretching (increases anterior impingement).' },
      { name:'Greater Trochanteric Pain Syndrome', ev:'ev-b', title:'Load management + hip abductor strengthening', body:'Avoid cross-leg sitting and hip adduction postures (compress trochanteric bursa). Isometric hip abduction (pain relief). Progressive hip abductor and ER strengthening. Avoid stretching IT band — compresses the trochanteric tendon. GTPS is a tendinopathy, not bursitis — treat with loading, not rest.' },
      { name:'Post-hip Arthroplasty', ev:'ev-a', title:'Enhanced recovery and progressive mobilisation', body:'Day 1 post-op: sit out and walk. Posterior approach precautions (avoid hip flexion >90°, IR, adduction) for 6-12 weeks. Anterior approach: fewer restrictions. Target: stair climbing by week 2, independent community ambulation by week 4, return to driving at 6-8 weeks. Progressive resistance training from week 6.' },
    ]
  },
  ankle: {
    name: 'Ankle & Foot', icon: '🦶',
    conditions: [
      { name:'Lateral Ankle Sprain', ev:'ev-a', title:'PEACE & LOVE protocol + early loading', body:'First 72h: PEACE (no anti-inflammatories). Then LOVE: early weightbearing as tolerated. Balance training from day 4: single-leg stance progressions. Peroneal strengthening. Figure-8 running before RTS. Early supervised physio reduces re-sprain by 49% at 1 year (Bleakley 2019).' },
      { name:'Achilles Tendinopathy', ev:'ev-a', title:'Heavy slow resistance loading programme', body:'Isometrics: 45s holds × 5 reps at 70% MVC, 2x/day (pain relief). HSR: calf raises progressing to unilateral, 3×8 at 8/10 RPE, 3x/week. 12-week minimum. VISA-A score for monitoring. No stretching of the Achilles — compressive loads at MTJ are primary irritant. Heel raise in shoe to reduce tendon compression.' },
      { name:'Plantar Fasciitis', ev:'ev-a', title:'Load management + intrinsic foot strengthening', body:'First-line: calf stretching, night splinting, foot orthoses for short-term relief. Intrinsic strengthening (toe curls, towel scrunching, short foot exercise). Shockwave therapy after 12 weeks if conservative treatment fails. Avoid complete rest — graded loading improves outcomes. Return to activity guided by first-step pain reduction.' },
      { name:'Syndesmotic / High Ankle Sprain', ev:'ev-b', title:'Extended protected weight-bearing + structured rehab', body:'Takes 2-3x longer than lateral sprain to heal. Protected weightbearing 2-4 weeks (more severe). ROM restoration focus: dorsiflexion mobility essential. Proprioception and peroneal strengthening. RTS: average 16-24 weeks for athletes. Syndesmotic fixation if >2mm diastasis.' },
    ]
  },
  elbow: {
    name: 'Elbow & Wrist', icon: '💪',
    conditions: [
      { name:'Lateral Epicondylalgia (Tennis Elbow)', ev:'ev-a', title:'Progressive eccentric/HSR loading', body:'Eccentric wrist extension (Tyler Twist), progressing to HSR with dumbbell. Grip strengthening. Cervical assessment (radiculopathy contribution). Shockwave therapy if >6 months. Corticosteroid injection: short-term superior to physio but worse at 12 months (Coombes 2013). Physio superior long-term — set patient expectations.' },
      { name:'Medial Epicondylalgia', ev:'ev-b', title:'Flexor-pronator loading + neural screening', body:'Assess for ulnar nerve involvement (cubital tunnel syndrome) — Tinel\'s and elbow flexion test. Wrist flexor and forearm pronator strengthening. Throwing mechanics assessment in athletes. Physiotherapy superior to corticosteroid injection at 12 months.' },
      { name:'Carpal Tunnel Syndrome', ev:'ev-b', title:'Neural mobilisation + night splinting', body:'Carpal bone mobilisation + neural mobilisation (median nerve slider). Night splinting in neutral (not flexion). Ergonomic modification. Physiotherapy equivalent to steroid injection at 12 months. Severe CTS with thenar wasting: refer for surgical decompression. Monitor with nerve conduction studies.' },
    ]
  },
};

// ─── RETURN TO SPORT PROTOCOLS ────────────────────────────────────────────────
const RTS_PROTOCOLS = [
  { title:'ACL Reconstruction RTS', phase:'Return to Sport', pc:'pb-rts', phases:[
    {n:'1',t:'Acute (0–6 wks)',d:'WBAT, quad sets, SLR, ROM 0–120°. NMES for AMI. Cryotherapy. Goals: full extension, minimal swelling, quad activation.'},
    {n:'2',t:'Strengthening (6–16 wks)',d:'Leg press, hamstring curl, hip strengthening, cycling. Target: LSI >70% quad strength on dynamometer.'},
    {n:'3',t:'Neuromuscular (4–6 mo)',d:'Plyometrics (bilateral → unilateral), agility, lateral cuts. Target: LSI >85% hop tests.'},
    {n:'4',t:'Sport-specific (7–9 mo)',d:'Full sport drills, competition simulation. RTS criteria: Quad LSI >90%, Hop LSI >90%, ACL-RSI >65. All 3 must be met.'},
  ], ev:'Grindem 2022 BJSM — Criteria-based clearance reduces re-injury by 75% vs time-based only.' },
  { title:'Rotator Cuff Repair RTS', phase:'Return to Sport', pc:'pb-rts', phases:[
    {n:'1',t:'Protection (0–6 wks)',d:'Sling. Pendulum exercises only. No active elevation. Passive ROM to patient tolerance.'},
    {n:'2',t:'Active ROM (6–12 wks)',d:'Active-assisted then active ROM. Scapular stabilisation. No resisted movement.'},
    {n:'3',t:'Strengthening (12–20 wks)',d:'Progressive RC strengthening (ER/IR with resistance band). Proprioceptive training.'},
    {n:'4',t:'Sport return (20–26 wks)',d:'Overhead athletes: interval throwing programme. Swimmers: gradual return to yardage. Full RTS at 6-9 months.'},
  ], ev:'Thigpen et al. 2020 — Post-op physio programme critical for outcomes independent of surgical technique.' },
  { title:'Achilles Tendinopathy', phase:'Rehab Protocol', pc:'pb-mod', phases:[
    {n:'1',t:'Isometric (wk 1–2)',d:'Bilateral calf raise holds 45s × 5 reps at 70% MVC, 2x/day. Immediate pain relief (Pain <3/10). Continue low-level activity.'},
    {n:'2',t:'Heavy slow resistance (wk 3–12)',d:'Bilateral → unilateral heel raises, 3×8 at 8/10 RPE, 3x/week. Target body weight load unilateral.'},
    {n:'3',t:'Energy storage (wk 12–16)',d:'Pogo jumps, calf raises on leg press, split squat. Progress when VAS <3/10 during.'},
    {n:'4',t:'RTS (wk 16+)',d:'Running programme: interval → continuous. VISA-A ≥80/100 target. Sport-specific plyometric load.'},
  ], ev:'Malliaras et al. 2023 BJSM — HSR superior to eccentric-only at 12 months (NRS -2.1).' },
  { title:'Knee OA Conservative', phase:'Rehabilitation', pc:'pb-rehab', phases:[
    {n:'1',t:'Education & pain management',d:'Explain OA biology. Address fear-avoidance. Short-term analgesia (topical NSAIDs) to facilitate exercise. Aquatic therapy if land exercise too painful.'},
    {n:'2',t:'Aerobic exercise (wk 2–8)',d:'150 min/week moderate: brisk walking, cycling, swimming. VAS ≤4/10 acceptable during exercise. Progress intensity weekly.'},
    {n:'3',t:'Resistance training (wk 4–16)',d:'Quad + hip strengthening 3x/week. Leg press, step-ups, mini-squats. Progressive load (RPE 6-7/10). Minimum 12 weeks for clinical effect.'},
    {n:'4',t:'Maintenance',d:'Exercise for life. Walking programme (≥6,000 steps/day). Weight management if BMI >25. Review annually. Surgical referral only after 6-month trial of conservative physiotherapy.'},
  ], ev:'Fransen et al. 2015 BJSM — Exercise reduces pain (SMD -0.49) and improves function (SMD 0.52).' },
  { title:'Lateral Ankle Sprain', phase:'Return to Sport', pc:'pb-rts', phases:[
    {n:'1',t:'PEACE (day 1–3)',d:'Protection, Elevation, Avoid anti-inflammatories, Compression, Education. No ice — vasoconstriction impairs healing. WBAT from day 1.'},
    {n:'2',t:'LOVE (day 4–14)',d:'Early loading and movement. Balance training from day 4. Peroneal activation. Pool walking if land-based too painful.'},
    {n:'3',t:'Strengthening (wk 2–6)',d:'Peroneal and tibialis strengthening. BOSU progressions. Single-leg squat. Hopping with controlled landing mechanics.'},
    {n:'4',t:'RTS (wk 4–8)',d:'Figure-8 running, lateral shuffles, cutting. Hop test >90% LSI. Brace for first 3 months of RTS for high ankle demand sports.'},
  ], ev:'Bleakley et al. 2019 BJSM — Early supervised exercise reduces re-sprain by 49% at 1 year.' },
  { title:'Low Back Pain', phase:'Rehabilitation', pc:'pb-rehab', phases:[
    {n:'1',t:'Acute (wk 1–2)',d:'Reassurance (prognosis is excellent: 90% recover). Maintain activity as tolerated. Avoid bed rest. Screen yellow flags (STarT Back). No imaging. Topical NSAIDs for short-term analgesia.'},
    {n:'2',t:'Subacute (wk 2–6)',d:'Motor control (TA activation, multifidus). Graded walking programme. Manual therapy + exercise > exercise alone. Directional preference assessment (McKenzie method).'},
    {n:'3',t:'Strengthening (wk 6–12)',d:'Progressive core and hip strengthening. Deadlift, hip hinge, squat patterns. Aerobic exercise 150 min/week. Address psychosocial factors if yellow flags present.'},
    {n:'4',t:'Return to work/sport',d:'Functional task simulation. Lifting mechanics training. Work hardening if manual occupation. Maintenance programme: exercise habits to prevent 50% recurrence rate.'},
  ], ev:'Foster et al. 2018 Lancet — Active rehab + biopsychosocial model superior to passive treatment.' },
];

// ─── MODALITIES ───────────────────────────────────────────────────────────────
const MODALITIES = [
  { icon:'💪', name:'Therapeutic Exercise', ev:'A', ec:'ev-a', desc:'Gold-standard for all MSK and respiratory conditions. Progressive loading drives tissue adaptation, endogenous opioid release, and central sensitisation desensitisation. First-line always — every other modality should facilitate participation in exercise.' },
  { icon:'🔵', name:'Manual Therapy (manipulation/mob)', ev:'B', ec:'ev-b', desc:'Short-term hypoalgesia via PAG activation and endogenous opioid release. Effective adjunct for acute LBP, cervical pain, shoulder, hip and ankle. NOT recommended as standalone — always combine with exercise prescription. Effects diminish without active reinforcement.' },
  { icon:'⚡', name:'TENS / Neurostimulation', ev:'B', ec:'ev-b', desc:'80Hz for gate control analgesia (acute pain); 2Hz for endorphin-mediated relief (chronic pain). Effective for facilitating exercise in painful conditions. Not recommended as standalone treatment. TENS during exercise is particularly effective for central sensitisation.' },
  { icon:'🌊', name:'Therapeutic Ultrasound', ev:'C', ec:'ev-c', desc:'Limited evidence for most chronic MSK conditions. Calcific shoulder (ESWT superior) and acute soft tissue may benefit. Phonophoresis for anti-inflammatory delivery has limited evidence. Not recommended as primary modality. Reserve for specific indications (phonophoresis, wound healing).' },
  { icon:'❄️', name:'Cryotherapy', ev:'B', ec:'ev-b', desc:'Post-surgical and acute injury analgesia. Reduces nerve conduction velocity, muscle spasm, and metabolic demand. Apply ≤20 min with barrier to skin. PEACE protocol replaces RICE — avoid NSAIDs in first 72h as they impair collagen synthesis. Ice still appropriate for post-op swelling management.' },
  { icon:'🔥', name:'Thermotherapy', ev:'B', ec:'ev-b', desc:'Increases tissue extensibility, muscle relaxation, and blood flow. Apply before stretching or exercise in chronic conditions. Contrast bathing (hot/cold) for subacute conditions. Shortwave diathermy for deep heating. Superficial heat is most accessible but limited depth penetration.' },
  { icon:'📍', name:'Dry Needling / IMS', ev:'B', ec:'ev-b', desc:'Intramuscular stimulation for active myofascial trigger points. Good evidence for neck, shoulder, and LBP. Local twitch response confirms trigger point. Contraindicated: blood disorders, local infection, pregnancy (select sites), pacemakers. Should be combined with active rehabilitation — not standalone treatment.' },
  { icon:'🦾', name:'Shockwave Therapy (ESWT)', ev:'A', ec:'ev-a', desc:'Strong evidence for calcific shoulder (90% calcium dissolution), chronic Achilles tendinopathy, and plantar fasciitis (after 12 weeks). Radial ESWT: 5 sessions × 2000 pulses at 0.12mJ/mm². Focused ESWT for deeper targets. Consider when guideline-based physiotherapy has failed at 12 weeks.' },
  { icon:'🧲', name:'NMES / Blood Flow Restriction', ev:'B', ec:'ev-b', desc:'NMES for quad re-education post-ACL (arthrogenic muscle inhibition). BFR training: allows strength gains at 20-30% 1RM load — ideal for post-surgical patients with load restrictions. BFR equipment required. Growing evidence for sarcopenia in older adults and CF-related muscle weakness.' },
  { icon:'🩹', name:'Taping (Kinesio / McConnell)', ev:'B', ec:'ev-b', desc:'McConnell patellar taping: best evidence in PFP — immediate pain reduction and VMO facilitation. Kinesio tape: limited evidence for structural support; useful for proprioceptive facilitation and lymphoedema management. Dynamic taping has emerging evidence for movement pattern correction.' },
  { icon:'💧', name:'Hydrotherapy / Aquatic', ev:'B', ec:'ev-b', desc:'Buoyancy reduces joint loading by 40-75% (hip/knee depth dependent). Ideal for early post-surgical rehabilitation and severe OA. Water resistance allows strengthening without compressive loading. Warm water (34-36°C) augments muscle relaxation. Equal exercise capacity gains vs land-based at 12 months in knee OA.' },
  { icon:'🧠', name:'Pain Neuroscience Education', ev:'A', ec:'ev-a', desc:'SMD -0.87 for catastrophising reduction (large effect size). Explain pain as an alarm system, not a damage meter. Address central sensitisation through reconceptualisation. PNE before exercise makes patients 4x more likely to engage fully with movement-based rehabilitation. Requires ≥2-3 dedicated sessions.' },
  { icon:'🔬', name:'Real-Time Ultrasound', ev:'B', ec:'ev-b', desc:'RUSI for biofeedback: deep stabiliser activation (TA, multifidus, pelvic floor). Objectively demonstrates contraction to patient — invaluable when patients cannot volitionally isolate deep muscles. Particularly useful: post-partum pelvic floor, chronic LBP, SCI, CF (diaphragm assessment). Requires training and appropriate equipment.' },
  { icon:'🏊', name:'Land vs Aquatic Exercise', ev:'B', ec:'ev-b', desc:'Aquatic exercise produces equivalent strength and cardiovascular gains to land-based exercise in OA, cardiac rehab, and early post-op. Advantages: pain reduction, fall safety, early loading. Disadvantages: access, cost, hygiene. Prescribe aquatic for patients who cannot achieve land-based exercise at therapeutic intensity.' },
];

// ─── ASSESSMENT TOOLS ─────────────────────────────────────────────────────────
const ASSESS_TOOLS = [
  { name:'LEFS (Lower Extremity Functional Scale)', joint:'Lower limb / Knee / Ankle', body:'20-item self-report for lower extremity function. Score: 0-80 (higher = better function). MCID: 9 points. Responsive to change in OA, tendinopathy, post-surgical. Takes 2 minutes. Free to use.', mcid:'MCID: 9 points (11.25%)' },
  { name:'DASH / QuickDASH', joint:'Upper extremity', body:'Disabilities of Arm, Shoulder and Hand. QuickDASH: 11-item abbreviated version. Score 0-100 (lower = better). MCID: 10-17 points. Validated across shoulder, elbow, wrist conditions. Sport/Work modules available.', mcid:'MCID: 10-17 points' },
  { name:'KOOS / WOMAC', joint:'Knee', body:'Knee injury and OA Outcome Score: 42 items, 5 subscales. KOOS-PS is the 7-item short form. WOMAC for OA specifically. MCID: 8-10 points per subscale. Use KOOS for younger/active patients; WOMAC for older OA populations.', mcid:'MCID: 8-10 points per subscale' },
  { name:'ACL-RSI (Return to Sport After Injury)', joint:'Knee / ACL', body:'12-item psychological readiness scale for ACL RTS. Score 0-100 (higher = more ready). Threshold: >65 for RTS clearance. Predicts re-injury risk. Free. Takes 3 minutes. Should be used at every RTS assessment — psychological readiness is as important as physical.', mcid:'Threshold: ≥65 for RTS' },
  { name:'Oswestry Disability Index (ODI)', joint:'Low back', body:'10-item disability questionnaire for LBP. Score 0-100%: 0-20% minimal, 21-40% moderate, 41-60% severe, >60% crippled. MCID: 10 points (10%). Score >40% signals need for psychologically-informed physiotherapy approach. Combine with STarT Back for risk stratification.', mcid:'MCID: 10 points' },
  { name:'STarT Back Screening Tool', joint:'Low back', body:'9-item psychosocial screening tool for LBP risk stratification. Three categories: low (physio-led exercise), medium (psychologically-informed physio), high (pain psychology + physio). Takes 3 minutes. Validated in Canadian populations. Free at keele.ac.uk/startback.', mcid:'Threshold-based: low/medium/high risk' },
  { name:'VISA-A / VISA-P', joint:'Achilles / Patellar tendon', body:'Victorian Institute of Sport Assessment. Achilles (VISA-A) and Patella (VISA-P). Score 0-100 (asymptomatic=100). MCID: 10-20 points. Use at every session to track tendinopathy loading tolerance. Target: ≥80/100 for RTS. Free at network.physio.', mcid:'Target: ≥80/100 for RTS' },
  { name:'NPRS / VAS / NRS', joint:'All conditions (pain)', body:'Numeric Pain Rating Scale: 0-10. NRS is preferred over VAS (simpler, equivalent psychometrics). Use consistently across all assessments. MCID: 1.5-2.0 points in most MSK conditions. Track pain at rest, activity, and worst/best — not just average. Record time of day for consistency.', mcid:'MCID: 1.5-2 points' },
  { name:'Tampa Scale for Kinesiophobia', joint:'Chronic pain / LBP / CRPS', body:'17-item fear of movement and re-injury questionnaire. Score 17-68 (higher = more kinesiophobia). Threshold: >37 indicates clinically significant kinesiophobia. Predicts disability and treatment response. High scores indicate need for graded exposure therapy before progressive loading.', mcid:'Clinical threshold: >37' },
  { name:'Berg Balance Scale', joint:'Neurological / Falls prevention', body:'14-item functional balance assessment. Score 0-56 (lower = greater fall risk). Clinical thresholds: <45 = high fall risk, <36 = near-certain fall risk. Takes 15-20 minutes. Standard in stroke, Parkinson\'s, geriatric physiotherapy. MCID: 4-7 points depending on population.', mcid:'MCID: 4-7 points; <45 = high fall risk' },
  { name:'Timed Up and Go (TUG)', joint:'Mobility / Falls / Geriatric', body:'Time to stand, walk 3m, return, sit. Normal: <12 seconds. >13.5s = significant fall risk. MCID: 1.4-3.4 seconds. Quick, equipment-free, widely validated. Dual-task TUG (count backwards) better predicts fall risk than single-task TUG in community-dwelling older adults.', mcid:'MCID: 1.4-3.4 seconds; >13.5s = fall risk' },
  { name:'6-Minute Walk Test (6MWT)', joint:'Cardiorespiratory / Cardiac / CF', body:'Self-paced 6-minute walking distance. Age/sex/height reference equations available (Enright, Troosters). MCID: 25m in COPD; 50m post-cardiac surgery; 30m in CF. Simple, reproducible, prognostic in respiratory disease. Standard in cardiac and pulmonary rehabilitation assessment.', mcid:'MCID: 25-54m depending on condition' },
];

// ─── NEWS FALLBACK STORIES ────────────────────────────────────────────────────
const FALLBACK_NEWS = [
  { title:"US Supreme Court ruling reshapes federal regulatory authority", source:"New York Times", category:"politics", summary:"The Supreme Court's decision significantly limits federal agencies' power to interpret ambiguous laws, shifting authority back to Congress and courts. Legal experts say the ruling will affect regulations from environmental policy to healthcare.", url:"https://www.nytimes.com", time:"1 hour ago" },
  { title:"Gaza ceasefire talks resume in Cairo as humanitarian crisis deepens", source:"Reuters", category:"world", summary:"Mediators from Egypt, Qatar and the US are pushing for a breakthrough in ceasefire negotiations. The UN has warned of catastrophic humanitarian conditions with 85% of Gaza's population displaced.", url:"https://www.reuters.com", time:"2 hours ago" },
  { title:"Bank of Canada holds interest rate amid trade war uncertainty", source:"CBC", category:"canada", summary:"The Bank of Canada kept its benchmark rate steady at 2.75%, citing ongoing uncertainty from US tariff measures affecting the Canadian economy. Governor Macklem signalled readiness to cut if economic conditions worsen.", url:"https://www.cbc.ca", time:"3 hours ago" },
  { title:"Toronto launches 100,000-home housing accelerator plan", source:"Toronto Star", category:"toronto", summary:"Mayor Olivia Chow unveiled an ambitious plan to fast-track 100,000 new homes over 10 years, including rezoning along transit corridors. Critics say provincial support is essential for the plan to succeed.", url:"https://www.thestar.com", time:"4 hours ago" },
  { title:"UK election: Labour wins historic majority but faces tough economic inheritance", source:"BBC", category:"politics", summary:"The Labour Party secured a commanding parliamentary majority in Thursday's UK general election. Prime Minister Keir Starmer faces immediate pressures including NHS waiting lists at record highs and sluggish economic growth.", url:"https://www.bbc.com/news", time:"5 hours ago" },
  { title:"Fed signals two rate cuts possible in 2025 as inflation cools", source:"Financial Times", category:"business", summary:"Federal Reserve minutes show policymakers increasingly confident that inflation is returning to target, with a majority seeing two quarter-point cuts as appropriate this year. Markets rallied on the release.", url:"https://www.ft.com", time:"6 hours ago" },
  { title:"Health Canada expands CFTR modulator access for children under 6 months", source:"CBC", category:"health", summary:"Health Canada approved elexacaftor-tezacaftor-ivacaftor for infants as young as 2 months with CF. The approval follows international paediatric safety data and significantly expands early treatment access in Canada.", url:"https://www.cbc.ca/health", time:"7 hours ago" },
  { title:"AI in medicine: new study shows diagnostic AI misses rare conditions", source:"New York Times", category:"science", summary:"A major NEJM study found that while AI tools match specialist accuracy for common conditions, they significantly underperform for rare and atypical presentations. Researchers caution against over-reliance without physician oversight.", url:"https://www.nytimes.com", time:"8 hours ago" },
  { title:"World leaders gather in Geneva for pandemic preparedness treaty", source:"Reuters", category:"world", summary:"WHO member states are meeting in Geneva to finalise a landmark pandemic preparedness accord. Negotiators are attempting to bridge divides on vaccine IP waiver provisions and technology transfer between high- and low-income nations.", url:"https://www.reuters.com", time:"9 hours ago" },
  { title:"FiveThirtyEight: Canadian federal election polling shows tight three-way race", source:"FiveThirtyEight", category:"data", summary:"New aggregate polling shows the Conservative Party at 36%, Liberals at 31%, and NDP at 22% — within the margin of error for a minority government outcome. Regional breakdowns show significant variation in Quebec and BC.", url:"https://www.fivethirtyeight.com", time:"10 hours ago" },
  { title:"The Athletic: NHL trade deadline reshapes playoff picture", source:"The Athletic", category:"sports", summary:"Several major trades ahead of the NHL deadline have significantly altered the Stanley Cup contender landscape. The Toronto Maple Leafs added defensive depth while the Colorado Avalanche parted with veteran forwards.", url:"https://www.theathletic.com", time:"11 hours ago" },
  { title:"China-Taiwan tensions rise after military exercises near strait", source:"BBC", category:"world", summary:"China conducted its largest military exercises near Taiwan in three years, involving naval vessels, fighter jets, and drones. Washington reiterated its commitment to Taiwan's security under the Taiwan Relations Act.", url:"https://www.bbc.com", time:"12 hours ago" },
  { title:"Global physiotherapy shortage: WHO calls for 2 million more rehabilitation workers", source:"Reuters", category:"health", summary:"The WHO released a global report showing a critical shortage of rehabilitation professionals, with physiotherapists most severely understaffed. Sub-Saharan Africa has one physiotherapist per 200,000 people versus one per 2,000 in Canada.", url:"https://www.reuters.com/health", time:"14 hours ago" },
  { title:"Economist analysis: Canada's productivity crisis and what it means for living standards", source:"The Economist", category:"business", summary:"Canada's productivity gap with the US has widened to its largest level since World War II. The Economist analysis points to housing costs, underinvestment in technology, and trade barriers as primary drivers.", url:"https://www.economist.com", time:"16 hours ago" },
  { title:"Washington Post investigation: climate records shattered across North America", source:"Washington Post", category:"science", summary:"An investigation finds that 2024 has already broken over 10,000 daily temperature records across North America. Scientists attribute the acceleration to a combination of El Niño and long-term anthropogenic warming.", url:"https://www.washingtonpost.com", time:"18 hours ago" },
];
