// ── MODALITIES WITH FULL CLINICAL PARAMETERS ─────────────────────────────────
const MODALITIES = [
  { icon:'💪', name:'Therapeutic Exercise', ev:'A', ec:'ev-a',
    desc:'Gold-standard first-line intervention. Progressive overload drives tissue adaptation, pain modulation via endogenous opioids, and functional restoration. All other modalities exist to facilitate participation in exercise.',
    params:[
      {label:'Strength (general)',         value:'3–4 sets × 8–12 reps at 70–80% 1RM · 2–3 min rest · 48h between sessions'},
      {label:'HSR (tendinopathy)',          value:'3 sets × 8–15 reps slow tempo (3s up/3s down) · 6–8/10 RPE · 3×/week'},
      {label:'Isometric (acute pain)',      value:'5 × 45s holds at 70% MVC · 2 min rest · 2×/day'},
      {label:'Aerobic',                     value:'150 min/week moderate · RPE 12–14 Borg 6-20 · 3–5 sessions/week'},
      {label:'Plyometric / RTS',            value:'Bilateral → unilateral → reactive · VAS ≤3/10 during · 72h between sessions'},
    ],
    contra:'Acute fracture, active DVT, unstable cardiac' },

  { icon:'⚡', name:'TENS', ev:'B', ec:'ev-b',
    desc:'Two distinct analgesic mechanisms: high frequency activates gate control (spinal inhibition); low frequency triggers endogenous opioid release. Best as adjunct to exercise — not standalone.',
    params:[
      {label:'Conventional (gate control)',  value:'80–150 Hz · pulse width 50–80 μs · strong comfortable tingling · 20–30 min · electrodes bracketing pain site'},
      {label:'Acupuncture-like (opioid)',    value:'1–4 Hz · pulse width 200–250 μs · visible muscle twitch · 20–30 min · acupuncture point placement'},
      {label:'Burst mode',                   value:'2 Hz bursts of 100 Hz · pulse width 200 μs · tolerable muscle twitch · 20–30 min'},
      {label:'Electrode placement',          value:'Surround pain site (bracketing) OR dermatomal/segmental; 2–4 electrodes'},
      {label:'Intensity guideline',          value:'Conventional: STRONG tingling, no muscle contraction · AL-TENS: visible motor twitch required'},
    ],
    contra:'Pacemaker, over carotid sinus, pregnancy (abdomen/pelvis), active DVT, malignancy over site' },

  { icon:'🧲', name:'NMES (Neuromuscular Electrical Stimulation)', ev:'B', ec:'ev-b',
    desc:'Electrically-evoked muscle contractions for re-education, strength gain, and overcoming arthrogenic muscle inhibition (AMI). Especially effective post-ACL, post-arthroplasty. BFR augments NMES effects.',
    params:[
      {label:'Muscle re-education (post-op)', value:'35–50 Hz · pulse width 300–400 μs · on:off 1:3 (10s on/30s off) · 10–15 contractions · 2×/day'},
      {label:'Strength augmentation',         value:'50–80 Hz · pulse width 400–600 μs · maximum tolerated contraction · 10 contractions × 10s · 3×/week'},
      {label:'Quad AMI post-ACL',             value:'50 Hz · VMO + distal quad electrode · concurrent volitional contraction essential · 15 min/session · daily weeks 1–4 post-op'},
      {label:'Blood Flow Restriction (BFR)',  value:'Load: 20–30% 1RM · cuff: 40–80% limb occlusion pressure · sets: 30-15-15-15 reps · rest: 30s between sets · 3×/week'},
      {label:'Respiratory (CF/COPD)',         value:'35 Hz · inspiratory muscle placement · 15–20 min/session · combined with breathing exercises'},
    ],
    contra:'Pacemaker, active DVT, malignancy over site, skin breakdown over electrodes, uncontrolled epilepsy' },

  { icon:'🌊', name:'Therapeutic Ultrasound', ev:'C', ec:'ev-c',
    desc:'Mechanical sound energy with thermal and non-thermal effects. Evidence is modest for most chronic MSK conditions — ESWT has largely replaced continuous US for tendinopathy. Pulsed US retains use for acute soft tissue and wound healing.',
    params:[
      {label:'SUPERFICIAL tissue (≤1 cm)',    value:'3 MHz · 0.5–1.5 W/cm² · pulsed 1:1 (50% duty) for non-thermal · 5–8 min · e.g. hand tendons, plantar fascia, AC joint'},
      {label:'DEEP tissue (2–5 cm)',           value:'1 MHz · 1.0–2.5 W/cm² · pulsed for non-thermal; continuous for thermal · 8–10 min · e.g. hip rotators, deep paraspinals, hamstring origin'},
      {label:'Thermal (heating) effect',       value:'Continuous mode, 1 MHz · 1.5–2.5 W/cm² · 8–10 min · increases tissue extensibility 10–15% at 40–45°C · precedes stretching'},
      {label:'Non-thermal (healing) effect',   value:'Pulsed 20% duty cycle · 0.5–1.0 W/cm² · 5–8 min · promotes cellular repair via cavitation and acoustic streaming'},
      {label:'Phonophoresis',                  value:'1 MHz continuous · 1.0–1.5 W/cm² · 5–8 min · gel: diclofenac or dexamethasone · limited but emerging evidence for drug penetration'},
      {label:'Treatment area rule',            value:'Move transducer at 1–2 cm/s in overlapping circles · treatment area ≤2× ERA of transducer · use coupling gel liberally'},
    ],
    contra:'Over malignancy, over active growth plates (paediatric), over metal implants, infected tissue, pregnancy, thrombophlebitis, over eyes/gonads, fresh fractures' },

  { icon:'💥', name:'Shockwave Therapy (ESWT)', ev:'A', ec:'ev-a',
    desc:'High-energy acoustic pressure waves. Strongest evidence for calcific shoulder, chronic Achilles tendinopathy, and plantar fasciitis after ≥12 weeks failed conservative management. Stimulates neovascularisation and collagen remodelling.',
    params:[
      {label:'Radial ESWT (superficial targets)', value:'2,000–3,000 impulses · 1.5–3.0 bar · 5–10 Hz · 5 weekly sessions · NO local anaesthesia (reduces efficacy) · most common device type'},
      {label:'Focused ESWT (deep targets)',        value:'1,500–2,000 impulses · 0.12–0.25 mJ/mm² energy flux density · ultrasound-guided targeting · 3–5 sessions weekly'},
      {label:'Calcific shoulder tendinopathy',      value:'Focused: 0.28 mJ/mm² · 2,000 impulses · 2 sessions 2 weeks apart · calcium dissolution in 90% at 6 months (Gerdesmeyer 2003 JBJS)'},
      {label:'Mid-portion Achilles tendinopathy',   value:'Radial: 2,500 impulses at 2.0–2.5 bar · 10 Hz · 5 weekly sessions · COMBINE with HSR exercise · superior to HSR alone at 12 months'},
      {label:'Plantar fasciitis (chronic)',          value:'Radial: 2,000 impulses · 2.0–3.0 bar · 10 Hz · 3 weekly sessions · after ≥12 weeks of failed stretching/orthotics'},
      {label:'Greater trochanteric pain syndrome',  value:'Radial: 2,000 impulses · 1.5–2.5 bar · 8 Hz · 3–5 sessions · combine with hip abductor loading programme'},
      {label:'Patellar tendinopathy',               value:'Radial: 2,000 impulses · 1.5–2.0 bar · 15 Hz · 3 weekly sessions · combine with decline squat HSR programme'},
    ],
    contra:'Coagulation disorders, anticoagulants (relative), local infection, over active growth plates, over lung tissue, malignancy, pregnancy' },

  { icon:'❄️', name:'Cryotherapy & the RICE → PEACE+LOVE Evidence Update', ev:'B', ec:'ev-b',
    desc:'ICE and RICE are no longer best practice for acute soft tissue injury. The 2020 PEACE & LOVE framework replaces RICE based on evidence that: (1) NSAIDs impair collagen synthesis, (2) ice delays satellite cell activity needed for muscle repair, (3) rest reduces loading stimulus critical for tissue remodelling.',
    params:[
      {label:'WHY ICING IS LESS SUPPORTED',       value:'Ice → vasoconstriction → reduces inflammatory cell delivery → impairs necessary inflammatory phase. Animal data (Takagi 2011 AJSM): icing delays muscle fibre regeneration by 1–2 weeks. Macrophages needed for myogenesis are delayed by cold-induced vasoconstriction.'},
      {label:'EVIDENCE AGAINST RICE',              value:'RICE coined by Dr Mirkin 1978 — he publicly retracted it in 2021. Hubbard et al. 2004: ice reduces muscle regeneration in animal models. Bleakley et al. 2012 BJSM: no strong RCT evidence ice improves long-term outcomes. NSAIDs in first 72h: block prostaglandin synthesis needed for tendon/ligament collagen formation.'},
      {label:'P — Protection (0–72h)',              value:'Unload/restrict movement 1–3 days ONLY (protect without immobilisation) · avoid activities causing sharp pain · early guarded movement preferred over splinting'},
      {label:'E — Elevation (0–72h)',               value:'Limb above heart level to reduce oedema · particularly effective for ankle/hand/forearm injuries'},
      {label:'A — Avoid anti-inflammatories (0–72h)',value:'NO NSAIDs (ibuprofen, naproxen) · NO ice as healing modality (comfort use is acceptable) · inflammation is necessary for tissue repair — do not suppress it'},
      {label:'C — Compression (0–72h)',              value:'Elastic bandage or compression sleeve · reduces interstitial bleeding and oedema · wear continuously (loosen if distal tingling)'},
      {label:'E — Education',                        value:'Active recovery expected · prognosis is good · movement is medicine · reassurance reduces catastrophising which predicts chronification'},
      {label:'L — Load (after 72h)',                 value:'Early mechanical loading at tolerable levels · graded return to activity · loading promotes collagen alignment and tissue tensile strength'},
      {label:'O — Optimism',                         value:'Catastrophising is a stronger predictor of outcome than imaging findings · address fear-avoidance early · positive prognosis messaging'},
      {label:'V — Vascularisation (after 72h)',      value:'Aerobic exercise (cycling, swimming, walking) for pain-free blood flow · promotes healing without compressive joint loading'},
      {label:'E — Exercise',                         value:'Progressive range of motion → strength → proprioception → sport-specific loading · individualised based on tissue tolerance'},
      {label:'When ice IS still appropriate',         value:'Post-surgical swelling (first 24–48h, not healing goal) · acute analgesia for severe pain (comfort only, ≤15 min with barrier) · acute joint haemarthrosis · NOT for muscle belly injuries where satellite cell activity is the priority'},
    ],
    contra:'Raynaud\'s phenomenon, cold urticaria, cryoglobulinaemia, impaired sensation, open wounds' },

  { icon:'🔴', name:'Low-Level Laser Therapy (LLLT / Photobiomodulation)', ev:'B', ec:'ev-b',
    desc:'Near-infrared light (600–1000 nm) stimulates mitochondrial cytochrome C oxidase, reducing oxidative stress and promoting cellular repair. Best evidence in lateral epicondylalgia, neck pain, and wound healing.',
    params:[
      {label:'General parameters',              value:'5–500 mW power · 630–1000 nm wavelength · 1–4 J/cm² dose · 30–90s per point · contact technique with firm pressure · protective eyewear mandatory'},
      {label:'Neck pain / cervical',             value:'4–6 J/cm² · 780–860 nm · 6–12 sessions over 2–4 weeks · C1–C5 facet joints and cervical paraspinals · 6 points per session'},
      {label:'Lateral epicondylalgia',           value:'0.5–1.0 J per point · 820–830 nm · 3 sites: extensor origin, lateral epicondyle, common extensor tendon mid-point · 3×/week × 4 weeks'},
      {label:'Achilles tendinopathy (adjunct)', value:'3–4 J/cm² · 820 nm · 5–6 points along tendon · 3×/week × 4–6 weeks · combine with HSR exercise · not standalone'},
      {label:'Wound healing',                    value:'0.5–2.0 J/cm² · 630–680 nm (red light) · pulsed 2–8 Hz · non-contact, 1 cm grid pattern over wound edges · 3×/week'},
    ],
    contra:'Over eyes (goggles mandatory for patient AND clinician), malignancy, thyroid gland, pregnancy (first trimester abdomen), photosensitising medications (methotrexate, tetracycline)' },

  { icon:'🙌', name:'Manual Therapy', ev:'B', ec:'ev-b',
    desc:'Joint mobilisation and manipulation. Short-term hypoalgesia via PAG-mediated endogenous opioid release and descending inhibitory pathway activation. Effects diminish rapidly without active exercise reinforcement.',
    params:[
      {label:'Grade I–II (pain/guarding)',    value:'Small amplitude oscillations at beginning of range · 2–3 min per technique · for acute pain and muscle guarding · does not stress tissue'},
      {label:'Grade III–IV (stiffness)',       value:'Large/small amplitude into resistance · 2–3 min · for joint stiffness · 1–2 techniques per session · reassess after each'},
      {label:'Grade V (manipulation, HVLAT)', value:'High velocity low amplitude thrust · single application per joint · primarily lumbar, thoracic, cervical · check VBI, RA, osteoporosis first'},
      {label:'MWM (Mulligan)',                 value:'Sustained AP/PA glide during active movement to end range · 10 reps × 3 sets · VAS must be ≤2/10 during · belt technique for lumbar'},
      {label:'Neural mobilisation',            value:'Slider technique: mobilise nerve by alternating tension at one end, slack at other · Tensioner: increase tension at both ends simultaneously (use cautiously acute) · 10 × 10 reps, 3×/day'},
      {label:'Session structure',              value:'Manual technique (5–10 min) → IMMEDIATELY follow with active exercise in newly acquired range → home exercise · do not use manual therapy without exercise component'},
    ],
    contra:'Fracture, malignancy, severe osteoporosis (manipulation), RA with atlantoaxial instability, VBI symptoms (cervical manip), active infection, undiagnosed pain with red flags' },

  { icon:'📍', name:'Dry Needling / IMS', ev:'B', ec:'ev-b',
    desc:'Intramuscular stimulation targeting active myofascial trigger points. Local twitch response (LTR) confirms accurate placement and is associated with greater pain reduction. Always combine with active rehabilitation.',
    params:[
      {label:'Needle specification',          value:'0.25–0.30 mm diameter · 25–50 mm length (depth-dependent) · sterile single-use acupuncture needles · 30–38 gauge'},
      {label:'Trigger point technique',       value:'Insert to TrP → wait for LTR (involuntary muscle twitch) → 2–4 piston movements or leave in situ 30–60s → 2–5 TrPs per session'},
      {label:'Segmental approach (IMS/Gunn)', value:'Multifidus and paraspinals at spinal level of radiculopathy · shorter needle residence (no pistoning) · 1–2 segmental levels per session'},
      {label:'Session frequency',             value:'2×/week initially → reduce to 1×/week as improvement plateaus · typically 4–8 sessions total · reassess after 3 sessions'},
      {label:'Best-evidence targets',         value:'Upper trapezius (neck pain/headache), infraspinatus (shoulder), gluteus medius (LBP/hip), gastrocnemius/soleus (Achilles/plantar fascia) — all have RCT evidence'},
      {label:'Post-needling soreness',        value:'Normal: 24–48h aching (similar to DOMS) · apply heat not ice after needling · gentle movement encouraged · warn patient pre-treatment'},
    ],
    contra:'Anticoagulants (relative, use thinner needle), local infection, lymphoedema in target area, needle phobia, pregnancy (specific abdominal/pelvic points), pacemaker (thoracic needling)' },

  { icon:'🩹', name:'Taping', ev:'B', ec:'ev-b',
    desc:'Multiple evidence-based approaches for different goals. McConnell for PFP has strongest RCT evidence. Kinesio tape: supported for oedema and proprioception — structural support claims are poorly supported.',
    params:[
      {label:'McConnell patellar (PFP)',       value:'Rigid sports tape · lateral→medial patellar glide correction · apply knee extended · immediately reduces VAS by 2.1 points (Crossley 2002 AJSM) · reapply every 3 days'},
      {label:'Kinesio — oedema reduction',    value:'Fan cut · 0% tension (paper-off) · distal to proximal · lifts skin 0.5–1 mm to improve lymphatic drainage · 3–5 days wear · up to 4 layers'},
      {label:'Kinesio — facilitation',        value:'25–35% tension · origin to insertion · activates muscle spindles · use for hypotonic or inhibited muscles · 3–5 days'},
      {label:'Kinesio — inhibition',          value:'15–25% tension · insertion to origin · reduces overactive muscle tone · use for hypertonic muscles · 3–5 days'},
      {label:'Dynamic tape (movement corr.)', value:'High-resistance elastic · modifies movement during activity · e.g. limit knee valgus in landing, reduce lumbar flexion moment arm'},
      {label:'Rigid ankle lace-up brace',     value:'Equivalent to rigid tape in RCTs · reduces re-sprain by 50% (Janssen 2014) · wear for sport for first 3 months of RTS · no proprioceptive benefit over tape'},
    ],
    contra:'Latex allergy (check Kinesio tape contents), fragile or broken skin, impaired sensation (unable to report tightness), poor peripheral circulation, oedema of cardiac origin' },

  { icon:'💧', name:'Hydrotherapy / Aquatic Physiotherapy', ev:'B', ec:'ev-b',
    desc:'Water immersion reduces joint loading by 40–75% (depth-dependent). Allows exercise at therapeutic intensity when land-based loading is contraindicated. Water temperature selection is critical and condition-dependent.',
    params:[
      {label:'Buoyancy off-loading by depth', value:'Hip depth: ~47% BW · umbilicus: ~57% BW off-load · axilla: ~75% BW off-load · titrate depth to control load in early post-op'},
      {label:'MSK pool temperature',          value:'33–35°C (warm): muscle relaxation, pain reduction · OA, fibromyalgia, early post-op, CF musculoskeletal'},
      {label:'Cardiac/COPD pool temp',        value:'28–32°C (cooler): reduces cardiac preload and demand · HOT pools (>36°C) are CONTRAINDICATED in cardiac patients'},
      {label:'Halliwick method (neuro)',       value:'4-phase: mental adjustment → static balance → turbulent gliding → swimming activities · 30–45 min/session · ideal MS, stroke, CP'},
      {label:'Bad Ragaz ring method',         value:'Isometric → isotonic → isokinetic in water via therapist-controlled turbulence · post-surgical strengthening with load restriction'},
      {label:'Transition to land-based',      value:'Begin land-based exercises at 6–8 weeks post-op (when loading tolerance permits) · do not continue aquatic indefinitely — specificity of land loading is required for return to full function'},
    ],
    contra:'Open wounds, active MRSA/VRE (pool contamination), severe uncontrolled hypertension, decompensated cardiac failure, fever, urinary incontinence without catheter (relative)' },

  { icon:'🧠', name:'Pain Neuroscience Education (PNE)', ev:'A', ec:'ev-a',
    desc:'Reconceptualisation of pain from a tissue-damage signal to a brain-produced output based on perceived threat. Largest-effect adjunct tool in chronic pain management. Must PRECEDE exercise for maximum engagement.',
    params:[
      {label:'Session 1 — Pain biology',       value:'45–60 min · "pain is an alarm, not a damage meter" · explain central sensitisation · use Explain Pain book (Moseley & Butler) · metaphors: alarm system, volume dial'},
      {label:'Session 2 — Reconceptualisation',value:'30–45 min · address specific patient beliefs · "my disc is crumbling / bone on bone" → evidence-based correction · introduce threat appraisal model · pain ≠ harm in CS'},
      {label:'Session 3 — Graded exposure',    value:'30 min · construct fear-avoidance hierarchy · begin graded exposure to feared movements · link neuroscience understanding to exercise engagement · address catastrophising in real-time'},
      {label:'Outcome measures',               value:'Pain Catastrophising Scale (PCS) baseline → target <20 · Tampa Scale for Kinesiophobia (TSK) → target <37 · reassess at 6 weeks · high scores = continue PNE before intensive loading'},
      {label:'Efficacy',                        value:'SMD -0.87 catastrophising (large effect) · SMD -0.58 disability · PNE before exercise: 4× more likely to engage fully with movement · superior to exercise alone for central sensitisation presentations'},
    ],
    contra:'None absolute. Acute pain: simplified brief version. Active psychosis or severe psychiatric condition: psychiatric input first. Not effective as standalone treatment — always combine with active rehabilitation' },
];


// ── EXPANDED TEACHING POINTS (5–7 per tab) ────────────────────────────────────
const TEACHING_POINTS = {

  cf: [
    {title:'CF Survival Has Changed Everything', body:'Median predicted survival for CF in Canada is now 58 years. Your physiotherapy role has fundamentally shifted: you are supporting a person through a complete life arc. Annual reviews must now address bone health (vertebral fractures in 30% of adults), pelvic floor dysfunction (71% stress incontinence), fertility and pregnancy planning, musculoskeletal aging, mental health, and long-term fitness — alongside traditional airway clearance.', source:'Cystic Fibrosis Canada Registry 2023'},
    {title:'Urinary Incontinence: Ask — They Won\'t Tell You', body:'71% of adult women with CF experience stress urinary incontinence during coughing, airway clearance, and exercise. It is severely underreported. Patients feel embarrassed, assume it is normal, or do not know physiotherapy can treat it. At every adult CF review, ask directly: "Do you ever leak urine when you cough, exercise, or do your airway clearance?" Pelvic floor physiotherapy produces 82–84% reduction in episodes at 12 weeks.', source:'Button et al. 2019; NACFC 2024'},
    {title:'ETI Does Not Replace Physiotherapy', body:'A dangerous misconception is that CFTR modulators eliminate physiotherapy need. ETI improves mucociliary clearance ~40% but does not normalise mucus rheology. VO₂ peak remains the strongest CF mortality predictor even on ETI (HR 2.6 per 10 mL/kg/min decrease). Structured exercise adds +3.2 mL/kg/min VO₂ above ETI alone (Cochrane 2022). You are not redundant — you are essential.', source:'Radtke et al. 2022 Cochrane; Tannenbaum et al. 2022'},
    {title:'Mental Health Drives Adherence', body:'Depression and anxiety in CF adolescents reduce physiotherapy adherence by 38–41%. Patients with PHQ-9 >10 complete 52% fewer airway clearance sessions. Motivational interviewing — brief 5-minute check-in using open questions and reflective listening — improves adherence significantly. Screen for mood as part of every CF physiotherapy assessment; it is a clinical variable as important as FEV1.', source:'Quon et al. 2023 Chest; NACFC 2023'},
    {title:'The Inhalation Sequence is a Drug Interaction', body:'Sequence matters pharmacokinetically: bronchodilator → wait 15 min → hypertonic saline or DNase → wait 30 min → airway clearance → inhaled antibiotics. Hypertonic saline pre-treatment increases sputum wet weight by 1.8g per session. Inhaled antibiotics post-clearance achieve higher airway drug concentrations because mucus obstruction has been partially cleared. Audit whether your patients follow this sequence — many do not.', source:'Dodd et al. 2021; CF Trust Guidelines 2022'},
    {title:'Exercise Testing: VO₂ Peak is Mortality Data', body:'Annual exercise capacity testing (CPET or 6MWT) provides prognostic data that spirometry cannot. VO₂ peak predicts 5-year mortality independent of FEV1, BMI, and microbiological status. Every CF physiotherapy programme should include exercise capacity as a primary outcome measure. Modified Godfrey protocol on cycle ergometer is the gold standard for CF; 6MWT is a validated surrogate when CPET unavailable.', source:'Lands et al. 2023 Lancet Respir Med'},
    {title:'Pregnancy in CF: Modified Physio Protocols', body:'Pregnancy rates in CF have tripled post-ETI. Physiotherapy must adapt: (1) avoid supine positions after 20 weeks gestation (compresses IVC), (2) modify airway clearance — sitting forward lean, lateral positions preferred, (3) address escalating urinary stress incontinence as gravid uterus increases pelvic floor load, (4) postpartum pelvic floor rehabilitation is essential given high baseline incontinence prevalence. CF pregnancy physiotherapy is an emerging subspecialty.', source:'Kazmerski et al. 2023 Lancet'},
  ],

  trikafta: [
    {title:'Triple Combination: What Each Drug Does', body:'Understanding ETI mechanism helps you explain it to patients and colleagues. Elexacaftor (VX-445): primary corrector — rescues F508del CFTR protein misfolding at the endoplasmic reticulum level. Tezacaftor (VX-661): second corrector — improves cell surface trafficking. Ivacaftor (VX-770): potentiator — keeps the CFTR channel open at the cell surface. Three drugs target three different steps in the same defective pathway.', source:'Middleton et al. 2019 NEJM'},
    {title:'5% of CF Patients Have No Modulator — Focus Your Care', body:'Class I mutations (premature stop codons — nonsense mutations like G542X, W1282X) affect ~8% of Canadian CF patients and produce no CFTR protein at all — modulators have nothing to correct or potentiate. These patients have no approved modulator therapy. They depend entirely on physiotherapy, nutrition, and antibiotics. Know your patient\'s mutation class; Class I patients deserve your most intensive physiotherapy focus.', source:'Shteinberg et al. 2021 Lancet'},
    {title:'De-escalating Airway Clearance on ETI: How to Decide', body:'When patients ask to reduce airway clearance on ETI, use objective data to guide the decision. Supporting reduction: sputum volume <5 mL/session consistently for 3 months, FEV1 stable, zero exacerbations in 12 months, self-reported symptom improvement. Minimum: once daily clearance is the floor — no evidence supports complete cessation. Increase back if exacerbation occurs, sputum volume increases, or FEV1 drops >5% from best.', source:'Elkins et al. 2024 J Cyst Fibros'},
    {title:'ETI Changes Sputum — Adjust Your Assessment', body:'On ETI, sputum volume decreases and viscosity changes. Patients may report "nothing comes up" but have audible secretions on auscultation. This doesn\'t mean clearance is unnecessary — it means the sputum is different. Use a combination of: auscultation before/after, patient symptom report, SpO₂ stability during clearance, and sputum colour (yellow-green = infection still present regardless of volume). Adapt your outcome measures, not your clinical reasoning.', source:'Boucher et al. 2021 JCI'},
    {title:'Microbiome Shift on ETI: Infection Control Still Critical', body:'ETI reduces Pseudomonas aeruginosa detection by 28% at 12 months and increases microbiome diversity. However, Stenotrophomonas maltophilia and non-tuberculous mycobacteria (NTM) are increasingly detected in ETI-treated patients — potentially as the competitive landscape shifts. Infection control precautions remain non-negotiable regardless of improved microbiological status. ETI-treated patients are not safe to share clinic space.', source:'Bell et al. 2022 Thorax'},
  ],

  airway: [
    {title:'The Inhalation Sequence: A Pharmacokinetic Prescription', body:'This is not optional. Sequence: bronchodilator (15 min) → hypertonic saline 7% or DNase (30 min) → airway clearance (20–40 min) → inhaled antibiotics. Evidence: HS pre-treatment increases sputum wet weight by 1.8g per session. Post-clearance antibiotics achieve higher airway drug concentrations. Audit your patients — many skip steps or reverse the sequence, substantially reducing effectiveness.', source:'Dodd et al. 2021 Chron Respir Dis'},
    {title:'PEP Mechanics: Collateral Ventilation is the Key', body:'PEP\'s mechanism relies on collateral ventilation channels (pores of Kohn, channels of Lambert). During PEP expiration, back-pressure keeps airways open and allows air to move through collateral channels to get behind trapped mucus. The subsequent FET/huff then moves this peripherally-recruited mucus proximally. Oscillating PEP adds 10–25 Hz vibration that reduces mucus viscoelasticity — shifting it from gel to sol phase, making it more mobile.', source:'Fagevik Olsén et al. 2022 Cochrane'},
    {title:'Central vs Peripheral Disease: Technique Changes', body:'Canadian functional MRI data shows autogenic drainage (AD) is superior for central bronchiectasis; oscillating PEP is superior for peripheral airway disease. Clinical clue to peripheral disease: minimal sputum during clearance despite significant symptoms, worse with exercise, and CT showing ground-glass opacities or air trapping rather than central bronchiectasis. These patients may benefit from HFCWO vest or changing to AD even if PEP preference was established.', source:'Svenningsen et al. 2023 Thorax'},
    {title:'FET vs Coughing: Why the Huff is Superior', body:'Forced expiration technique (huff/FET) produces 3× greater mucus clearance than coughing with significantly less dynamic airway collapse. During a cough, intrapleural pressure >150 mmHg compresses airways and traps mucus distal to the compression point. During a huff (open-glottis expiration), this compression is reduced, allowing more effective peripheral secretion clearance. Teach your patients to huff, not cough — and teach it correctly (open mouth, "haaah" sound, not throat clearing).', source:'Lee et al. 2018 Breathe'},
    {title:'Exercise Augments Airway Clearance by 15–20%', body:'Moderate-to-vigorous exercise produces 15–20% more mucus clearance over 24 hours compared to rest alone. Mechanisms: increased minute ventilation → increased turbulent airflow → mucus shear forces; hyperventilation → collateral ventilation → mobilises peripheral secretions; hyperpnoea → increased cough reflex sensitivity. Prescribe exercise BEFORE airway clearance when possible — the mobilised secretions are then cleared by the subsequent AC session.', source:'Dwyer et al. 2011 Expert Rev Respir Med'},
    {title:'Session Duration: Quality Over Length', body:'Optimal airway clearance session: 20–30 minutes of active technique, not 45–60 minutes of passive percussion. Research shows diminishing returns after 30 minutes of active techniques. Key quality indicators: (1) sputum expectoration should occur within first 10 minutes, (2) colour should shift lighter over the session (mobilising deeper, older secretions), (3) SpO₂ should not drop >4% — if it does, increase breathing control phases. Prescribe an effective 25-minute session rather than a sloppy 45-minute one.', source:'CF Trust Guidelines 2022'},
    {title:'HFCWO Vests: Who Benefits Most', body:'High-frequency chest wall oscillation (ThAIRapy/VEST) is equivalent to conventional CPT for FEV1 preservation and superior for patient adherence in selected patients. Best candidates: patients who live alone without a physiotherapy partner for manual CPT; CF-related arthritis limiting PEP device use; repeated demonstrated poor adherence with other devices; severe fatigue limiting active techniques. Cost is high (~$15,000 CAD) but justified by adherence gains. Advocate for coverage through provincial plans.', source:'Morrison & Agnew 2014 Cochrane'},
  ],

  pt: [
    {title:'Physiotherapy Scope Across the Lifespan', body:'Physiotherapists practise from NICU (premature infant motor development) to end-of-life palliative care (positioning, dyspnoea management). Scope encompasses: musculoskeletal, neurology, cardiorespiratory, oncology rehabilitation, pelvic health, geriatrics, paediatrics, occupational health, sports, and now mental health (exercise as treatment). In Canada, extended practice roles include ordering specific investigations and prescribing some medications in certain provinces.', source:'CPA Practice Framework 2023'},
    {title:'Exercise IS a Treatment for Depression: Prescribe It', body:'Meta-analysis of 33 RCTs: supervised aerobic exercise reduces depression symptoms with SMD -0.79 (large effect) — equivalent to moderate antidepressant medication. Effective dose: 3 sessions/week, 45–60 min, moderate intensity (RPE 12–14), 12 weeks minimum. Physiotherapist-supervised exercise is superior to unsupervised. For every patient with chronic disease and comorbid depression, document exercise for mental health as an explicit treatment goal in your notes.', source:'Stubbs et al. 2016 J Affect Disord'},
    {title:'Cardiac Rehab: One of Our Strongest Evidence Bases', body:'Exercise-based cardiac rehabilitation reduces cardiovascular mortality by 26% and readmission by 18% (63-trial Cochrane meta-analysis). Physiotherapist-led cardiac rehab is among the most evidence-based interventions in all of medicine. Yet <30% of eligible Canadians access it. If you work anywhere near cardiovascular patients: advocate loudly for referral, and consider whether cardiac rehab could be delivered in your setting.', source:'Anderson et al. 2016 JACC'},
    {title:'Falls Prevention: You Can Save Lives', body:'108-trial Cochrane review: exercise reduces falls by 23% and fall-related injuries by 27%. The Otago Exercise Programme (home-based, 14 strengthening + 12 balance exercises, 3×/week) reduces falls by 35% and is cost-effective. Add Tai Chi (24-form Yang): 43% fall rate reduction. Home hazard assessment adds 19%. Every older adult (>65) in your caseload should receive falls risk screening (TUG, Berg Balance Scale) and targeted falls prevention — it is part of our professional obligation.', source:'Sherrington et al. 2019 Cochrane'},
    {title:'Pelvic Floor Is General Physiotherapy', body:'PFMT is first-line treatment for stress, urgency, and mixed urinary incontinence (endorsed NICE, EAU, SOGC). Effective PFMT prescription: 8–12 contractions (endurance holds 8–10s + quick-flick contractions), 3 sets/day, minimum 12 weeks. Every physiotherapist should be able to teach a pelvic floor contraction and prescribe basic PFMT — internal examination requires specialised training, but external prescription does not. Screen routinely in: CF, post-partum, post-prostatectomy, prolapse.', source:'Dumoulin et al. 2018 Cochrane'},
    {title:'Oncology Exercise: Evidence Overturns Old Advice', body:'International consensus across 2017–2019: exercise is safe and beneficial during and after ALL cancer treatments. Aerobic + resistance training during chemotherapy: reduces fatigue (counterintuitively — exercise decreases cancer-related fatigue), nausea, depression, and treatment toxicity. Resistance training preserves lean mass lost during treatment. The old advice to "rest and recover" during cancer treatment is now considered harmful. Every cancer patient deserves an exercise referral — this is no longer optional.', source:'Campbell et al. 2019 MSSE'},
    {title:'Telehealth Physiotherapy: Non-Inferior for Maintenance', body:'Systematic review evidence confirms telehealth physiotherapy is non-inferior to in-person delivery for: MSK conditions (stable), COPD pulmonary rehabilitation, cardiac rehabilitation follow-up, and CF physiotherapy monitoring. Patient satisfaction is high; adherence is equivalent. For Canadian physiotherapists, this expands our reach to rural and remote populations — and is now a permanent service model, not a COVID workaround. Telehealth should be proactively offered as a delivery option, not only suggested when in-person access is difficult.', source:'Cottrell et al. 2017 J Telemed Telecare'},
  ],

  pain: [
    {title:'5 Signs You Are Missing Central Sensitisation', body:'When you see these, peripheral tissue treatment will fail: (1) pain disproportionate to tissue findings or injury severity, (2) allodynia — pain from normally non-painful stimuli (e.g. light touch on skin), (3) hyperalgesia — exaggerated pain response to mildly painful stimuli, (4) widespread pain beyond original injury site, (5) pain worsening with physical AND emotional/psychological stressors. CS requires PNE + graded exposure + often psychological support.', source:'Woolf 2011 Pain; Nijs et al. 2020'},
    {title:'Budapest Criteria: Know Them Cold', body:'CRPS diagnosis requires: ≥1 symptom in ≥3 categories AND ≥1 sign in ≥2 categories. The 4 categories: (1) Sensory — allodynia, hyperalgesia; (2) Vasomotor — skin temperature asymmetry >1°C, colour changes; (3) Sudomotor/Oedema — sweating asymmetry, oedema; (4) Motor/Trophic — reduced ROM, weakness, tremor, skin/hair/nail/bone changes. You will see CRPS before rheumatology or pain specialists do — know when to flag it.', source:'Harden et al. 2023 Pain'},
    {title:'GMI: The Three-Phase Protocol in Practice', body:'Phase 1 (Weeks 1–2): Laterality discrimination — Recognise™ app, 5 min × 2/day. Target >80% accuracy at <2s response time before advancing. Phase 2 (Weeks 3–4): Imagined movements in pain-free range, 3×/day, 10 reps each. Begin with contralateral limb imagining. Phase 3 (ongoing): Mirror visual feedback — affected limb behind mirror, unaffected limb performs movements while patient watches reflection. Never skip Phase 1 — starting with mirror therapy without laterality training fails in most cases.', source:'Moseley et al. 2022 Pain'},
    {title:'Catastrophising Predicts Outcome Better Than MRI', body:'The Pain Catastrophising Scale (PCS) — three subscales of rumination, magnification, and helplessness — predicts chronic disability, treatment non-response, and opioid escalation better than structural imaging findings, pain intensity, or injury severity. PCS >30 = high risk for chronification. Measure it at intake for every chronic pain patient. Scores >30 indicate PNE is the first treatment priority, before loading or exercise.', source:'Sullivan et al. 2001; Louw et al. 2021'},
    {title:'Ketamine + Physiotherapy: Coordinate the Timing', body:'Subanaesthetic ketamine infusion (IV, outpatient) reduces NMDA receptor-mediated central sensitisation — creating a pain window. Canadian data shows physiotherapy within 48h of infusion increases response rate from 61% to 79%. Coordinate with the pain anaesthesiologist to schedule your most intensive sessions in the 2–5 days post-infusion: desensitisation hierarchies, graded movement, functional rehabilitation, mirror therapy. Do not waste the window.', source:'Schwartzman et al. 2023 Clin J Pain'},
    {title:'Mirror Therapy Setup: Practical Steps', body:'Mirror box: vertical mirror bisecting patient\'s midline; affected limb hidden behind mirror; unaffected limb in front. Session setup: patient looks only at mirror reflection, not at affected limb. Start simple: finger flexion/extension, wrist circles — 10–15 min/day. Progress to bimanual movements. Key instruction: "Believe the reflection is your affected hand." Common errors: starting too complex, insufficient time, patient breaking gaze. CRPS patients may find it distressing initially — start with 5 minutes and build tolerance.', source:'Ramachandran & Altschuler 2009 Brain'},
    {title:'Graded Exposure vs Graded Activity: Know the Difference', body:'Graded activity: increases activity quota irrespective of pain — useful for deconditioned patients without significant fear-avoidance. Graded exposure: specifically targets feared movements/activities identified on a fear hierarchy — uses PNE and behavioural experiments to challenge threat appraisal. When the Tampa Scale >37 or PCS >30, use graded exposure — not just graded activity. Fear of movement must be specifically addressed, not just gradually increased activity loading.', source:'Vlaeyen & Linton 2000; Nijs et al. 2020'},
  ],

  auto: [
    {title:'Your Emergency AD Protocol: Memorise This', body:'AD can be fatal — BP can exceed 300 mmHg systolic. Sequence: (1) IMMEDIATELY sit upright — lowers BP 15–20 mmHg via orthostatic effect — do not leave patient supine, (2) Loosen ALL constricting clothing, shoes, orthotics, catheter straps immediately, (3) Check catheter — kinked or full drainage bag is the #1 trigger; if blocked, catheterise now, (4) Check for fecal impaction, tight clothing, pressure sore, ingrown toenail, (5) Call emergency if BP remains >150/100 after 5 minutes with trigger addressed. Do not continue physiotherapy during an episode.', source:'Krassioukov et al. 2021 Spinal Cord'},
    {title:'Pre-Session SCI Checklist: 2 Minutes That Prevent Emergencies', body:'Before every session with SCI above T6: (1) Ask about last void and bladder sensation, (2) Inspect catheter — drainage bag <2/3 full? drainage tube not kinked? (3) Record baseline BP — your personal "stop treatment" threshold is +20 mmHg systolic above this, (4) Check for constricting clothing, tight shoes, pressure areas, (5) Ask about bowel status (last bowel care). Document baseline BP in every session note — you need this data if AD develops.', source:'Currie et al. 2022 J Physiother'},
    {title:'The Top 5 AD Triggers in Physiotherapy Settings', body:'(1) Bladder distension — 75–85% of episodes; check catheter before every session, (2) Mat work and transfers — position changes cause pressure distribution shifts below injury level, (3) Spasticity from handling — stretch or position changes can trigger spasms that sensitise AD pathways, (4) Skin pressure from equipment — check AFOs, splints, positioning aids are not too tight, (5) Unknown noxious stimuli — patients cannot feel pressure sores, fractures, or infections below injury level; inspect what you cannot see.', source:'Krassioukov et al. 2021'},
    {title:'Cardiovascular Risk of Repeated AD: Think Long-Term', body:'Each AD episode is a hypertensive surge that contributes to cumulative cardiovascular pathology. After 15 years of SCI: 67% of patients with >3 AD episodes/year show echocardiographic evidence of LV hypertrophy and diastolic dysfunction. This means trigger prevention is a cardiovascular health intervention, not just acute safety. Document every episode in session notes, report to medical team, and advocate loudly for optimised bowel and bladder programmes — this is cardioprotection.', source:'Myers et al. 2022 J Spinal Cord Med'},
    {title:'Boosting: Your Professional Duty to Act', body:'Intentional AD induction ("boosting") is banned by the IPC but used by ~16% of eligible Paralympic athletes. Recognition: facial flushing, excessive sweating above injury level, pilomotor erection, bradycardia with acute BP spike — just before or during competition. As a physiotherapist or exercise physiologist working with Paralympic athletes you have both a professional and ethical duty: (1) recognise these signs, (2) alert the chief medical officer immediately, (3) never facilitate boosting even if pressured by athlete or coaching staff. This is a banned doping method and a medical emergency.', source:'Bhambhani et al. 2021 BJSM'},
    {title:'Sexual Health and AD: Have the Conversation', body:'68% of SCI patients experience AD during sexual activity — but 82% have never been educated about it by their healthcare team. Your role at discharge: (1) Explain that sexual activity can trigger AD, (2) Provide written emergency AD protocol that patient can share with partners, (3) Discuss positioning options that reduce AD risk during intercourse, (4) Validate sexual health as a legitimate rehabilitation goal. Do not wait for the patient to raise the topic — they are waiting for you.', source:'Elliott et al. 2023 J Sex Med'},
  ],
};
